package com.lfscheidegger.jfacet.shade.expression.vector;

import org.junit.Test;

import static org.junit.Assert.*;

/**
 * Unit tests for {@code BVector3.Primitive}
 */
public class BVector4PrimitiveTest {

  private final BVector4.Primitive vec;

  public BVector4PrimitiveTest() {
    vec = new BVector4.Primitive(true, false, false, false);
  }

  @Test
  public void testConstructors() {
    assertTrue(vec.getX());
    assertFalse(vec.getY());
    assertFalse(vec.getZ());
    assertFalse(vec.getW());
  }

  @Test
  public void testGetters() {
    boolean x = vec.getX();
    boolean y = vec.getY();
    boolean z = vec.getZ();
    boolean w = vec.getW();

    assertTrue(x);
    assertFalse(y);
    assertFalse(z);
    assertFalse(w);

    assertTrue(vec.get(0) == vec.getX());
    assertTrue(vec.get(1) == vec.getY());
    assertTrue(vec.get(2) == vec.getZ());
    assertTrue(vec.get(3) == vec.getW());
  }

  @Test
  @SuppressWarnings("all")
  public void testSwizzleXYZW() {
    assertTrue(vec.x().get() == true);
    assertTrue(vec.y().get() == false);
    assertTrue(vec.z().get() == false);
    assertTrue(vec.w().get() == false);

    assertEquals(vec.x().x().get(), new BVector2.Primitive(true, true));
    assertEquals(vec.x().y().get(), new BVector2.Primitive(true, false));
    assertEquals(vec.x().z().get(), new BVector2.Primitive(true, false));
    assertEquals(vec.x().w().get(), new BVector2.Primitive(true, false));
    assertEquals(vec.y().x().get(), new BVector2.Primitive(false, true));
    assertEquals(vec.y().y().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.y().z().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.y().w().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.z().x().get(), new BVector2.Primitive(false, true));
    assertEquals(vec.z().y().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.z().z().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.z().w().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.w().x().get(), new BVector2.Primitive(false, true));
    assertEquals(vec.w().y().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.w().z().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.w().w().get(), new BVector2.Primitive(false, false));

    assertEquals(vec.x().x().x().get(), new BVector3.Primitive(true, true, true));
    assertEquals(vec.x().x().y().get(), new BVector3.Primitive(true, true, false));
    assertEquals(vec.x().x().z().get(), new BVector3.Primitive(true, true, false));
    assertEquals(vec.x().x().w().get(), new BVector3.Primitive(true, true, false));
    assertEquals(vec.x().y().x().get(), new BVector3.Primitive(true, false, true));
    assertEquals(vec.x().y().y().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.x().y().z().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.x().y().w().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.x().z().x().get(), new BVector3.Primitive(true, false, true));
    assertEquals(vec.x().z().y().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.x().z().z().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.x().z().w().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.x().w().x().get(), new BVector3.Primitive(true, false, true));
    assertEquals(vec.x().w().y().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.x().w().z().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.x().w().w().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.y().x().x().get(), new BVector3.Primitive(false, true, true));
    assertEquals(vec.y().x().y().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.y().x().z().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.y().x().w().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.y().y().x().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.y().y().y().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.y().y().z().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.y().y().w().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.y().z().x().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.y().z().y().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.y().z().z().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.y().z().w().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.y().w().x().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.y().w().y().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.y().w().z().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.y().w().w().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.z().x().x().get(), new BVector3.Primitive(false, true, true));
    assertEquals(vec.z().x().y().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.z().x().z().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.z().x().w().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.z().y().x().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.z().y().y().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.z().y().z().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.z().y().w().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.z().z().x().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.z().z().y().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.z().z().z().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.z().z().w().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.z().w().x().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.z().w().y().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.z().w().z().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.z().w().w().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.w().x().x().get(), new BVector3.Primitive(false, true, true));
    assertEquals(vec.w().x().y().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.w().x().z().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.w().x().w().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.w().y().x().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.w().y().y().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.w().y().z().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.w().y().w().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.w().z().x().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.w().z().y().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.w().z().z().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.w().z().w().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.w().w().x().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.w().w().y().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.w().w().z().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.w().w().w().get(), new BVector3.Primitive(false, false, false));

    assertEquals(vec.x().x().x().x(), new BVector4.Primitive(true, true, true, true));
    assertEquals(vec.x().x().x().y(), new BVector4.Primitive(true, true, true, false));
    assertEquals(vec.x().x().x().z(), new BVector4.Primitive(true, true, true, false));
    assertEquals(vec.x().x().x().w(), new BVector4.Primitive(true, true, true, false));
    assertEquals(vec.x().x().y().x(), new BVector4.Primitive(true, true, false, true));
    assertEquals(vec.x().x().y().y(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.x().x().y().z(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.x().x().y().w(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.x().x().z().x(), new BVector4.Primitive(true, true, false, true));
    assertEquals(vec.x().x().z().y(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.x().x().z().z(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.x().x().z().w(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.x().x().w().x(), new BVector4.Primitive(true, true, false, true));
    assertEquals(vec.x().x().w().y(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.x().x().w().z(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.x().x().w().w(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.x().y().x().x(), new BVector4.Primitive(true, false, true, true));
    assertEquals(vec.x().y().x().y(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.x().y().x().z(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.x().y().x().w(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.x().y().y().x(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.x().y().y().y(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().y().y().z(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().y().y().w(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().y().z().x(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.x().y().z().y(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().y().z().z(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().y().z().w(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().y().w().x(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.x().y().w().y(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().y().w().z(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().y().w().w(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().z().x().x(), new BVector4.Primitive(true, false, true, true));
    assertEquals(vec.x().z().x().y(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.x().z().x().z(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.x().z().x().w(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.x().z().y().x(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.x().z().y().y(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().z().y().z(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().z().y().w(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().z().z().x(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.x().z().z().y(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().z().z().z(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().z().z().w(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().z().w().x(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.x().z().w().y(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().z().w().z(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().z().w().w(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().w().x().x(), new BVector4.Primitive(true, false, true, true));
    assertEquals(vec.x().w().x().y(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.x().w().x().z(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.x().w().x().w(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.x().w().y().x(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.x().w().y().y(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().w().y().z(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().w().y().w(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().w().z().x(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.x().w().z().y(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().w().z().z(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().w().z().w(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().w().w().x(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.x().w().w().y(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().w().w().z(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.x().w().w().w(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.y().x().x().x(), new BVector4.Primitive(false, true, true, true));
    assertEquals(vec.y().x().x().y(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.y().x().x().z(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.y().x().x().w(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.y().x().y().x(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.y().x().y().y(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.y().x().y().z(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.y().x().y().w(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.y().x().z().x(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.y().x().z().y(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.y().x().z().z(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.y().x().z().w(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.y().x().w().x(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.y().x().w().y(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.y().x().w().z(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.y().x().w().w(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.y().y().x().x(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.y().y().x().y(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.y().y().x().z(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.y().y().x().w(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.y().y().y().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.y().y().y().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().y().y().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().y().y().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().y().z().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.y().y().z().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().y().z().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().y().z().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().y().w().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.y().y().w().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().y().w().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().y().w().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().z().x().x(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.y().z().x().y(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.y().z().x().z(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.y().z().x().w(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.y().z().y().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.y().z().y().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().z().y().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().z().y().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().z().z().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.y().z().z().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().z().z().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().z().z().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().z().w().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.y().z().w().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().z().w().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().z().w().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().w().x().x(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.y().w().x().y(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.y().w().x().z(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.y().w().x().w(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.y().w().y().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.y().w().y().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().w().y().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().w().y().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().w().z().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.y().w().z().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().w().z().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().w().z().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().w().w().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.y().w().w().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().w().w().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.y().w().w().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().x().x().x(), new BVector4.Primitive(false, true, true, true));
    assertEquals(vec.z().x().x().y(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.z().x().x().z(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.z().x().x().w(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.z().x().y().x(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.z().x().y().y(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.z().x().y().z(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.z().x().y().w(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.z().x().z().x(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.z().x().z().y(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.z().x().z().z(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.z().x().z().w(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.z().x().w().x(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.z().x().w().y(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.z().x().w().z(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.z().x().w().w(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.z().y().x().x(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.z().y().x().y(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.z().y().x().z(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.z().y().x().w(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.z().y().y().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.z().y().y().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().y().y().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().y().y().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().y().z().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.z().y().z().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().y().z().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().y().z().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().y().w().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.z().y().w().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().y().w().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().y().w().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().z().x().x(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.z().z().x().y(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.z().z().x().z(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.z().z().x().w(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.z().z().y().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.z().z().y().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().z().y().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().z().y().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().z().z().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.z().z().z().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().z().z().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().z().z().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().z().w().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.z().z().w().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().z().w().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().z().w().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().w().x().x(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.z().w().x().y(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.z().w().x().z(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.z().w().x().w(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.z().w().y().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.z().w().y().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().w().y().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().w().y().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().w().z().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.z().w().z().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().w().z().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().w().z().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().w().w().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.z().w().w().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().w().w().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.z().w().w().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().x().x().x(), new BVector4.Primitive(false, true, true, true));
    assertEquals(vec.w().x().x().y(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.w().x().x().z(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.w().x().x().w(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.w().x().y().x(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.w().x().y().y(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.w().x().y().z(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.w().x().y().w(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.w().x().z().x(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.w().x().z().y(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.w().x().z().z(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.w().x().z().w(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.w().x().w().x(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.w().x().w().y(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.w().x().w().z(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.w().x().w().w(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.w().y().x().x(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.w().y().x().y(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.w().y().x().z(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.w().y().x().w(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.w().y().y().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.w().y().y().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().y().y().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().y().y().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().y().z().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.w().y().z().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().y().z().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().y().z().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().y().w().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.w().y().w().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().y().w().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().y().w().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().z().x().x(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.w().z().x().y(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.w().z().x().z(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.w().z().x().w(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.w().z().y().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.w().z().y().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().z().y().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().z().y().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().z().z().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.w().z().z().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().z().z().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().z().z().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().z().w().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.w().z().w().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().z().w().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().z().w().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().w().x().x(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.w().w().x().y(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.w().w().x().z(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.w().w().x().w(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.w().w().y().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.w().w().y().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().w().y().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().w().y().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().w().z().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.w().w().z().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().w().z().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().w().z().w(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().w().w().x(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.w().w().w().y(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().w().w().z(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.w().w().w().w(), new BVector4.Primitive(false, false, false, false));

  }

  @Test
  @SuppressWarnings("all")
  public void testSwizzleRGBA() {
    assertTrue(vec.r().get() == true);
    assertTrue(vec.g().get() == false);
    assertTrue(vec.b().get() == false);
    assertTrue(vec.a().get() == false);

    assertEquals(vec.r().r().get(), new BVector2.Primitive(true, true));
    assertEquals(vec.r().g().get(), new BVector2.Primitive(true, false));
    assertEquals(vec.r().b().get(), new BVector2.Primitive(true, false));
    assertEquals(vec.r().a().get(), new BVector2.Primitive(true, false));
    assertEquals(vec.g().r().get(), new BVector2.Primitive(false, true));
    assertEquals(vec.g().g().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.g().b().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.g().a().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.b().r().get(), new BVector2.Primitive(false, true));
    assertEquals(vec.b().g().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.b().b().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.b().a().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.a().r().get(), new BVector2.Primitive(false, true));
    assertEquals(vec.a().g().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.a().b().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.a().a().get(), new BVector2.Primitive(false, false));

    assertEquals(vec.r().r().r().get(), new BVector3.Primitive(true, true, true));
    assertEquals(vec.r().r().g().get(), new BVector3.Primitive(true, true, false));
    assertEquals(vec.r().r().b().get(), new BVector3.Primitive(true, true, false));
    assertEquals(vec.r().r().a().get(), new BVector3.Primitive(true, true, false));
    assertEquals(vec.r().g().r().get(), new BVector3.Primitive(true, false, true));
    assertEquals(vec.r().g().g().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.r().g().b().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.r().g().a().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.r().b().r().get(), new BVector3.Primitive(true, false, true));
    assertEquals(vec.r().b().g().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.r().b().b().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.r().b().a().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.r().a().r().get(), new BVector3.Primitive(true, false, true));
    assertEquals(vec.r().a().g().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.r().a().b().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.r().a().a().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.g().r().r().get(), new BVector3.Primitive(false, true, true));
    assertEquals(vec.g().r().g().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.g().r().b().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.g().r().a().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.g().g().r().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.g().g().g().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.g().g().b().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.g().g().a().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.g().b().r().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.g().b().g().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.g().b().b().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.g().b().a().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.g().a().r().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.g().a().g().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.g().a().b().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.g().a().a().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.b().r().r().get(), new BVector3.Primitive(false, true, true));
    assertEquals(vec.b().r().g().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.b().r().b().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.b().r().a().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.b().g().r().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.b().g().g().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.b().g().b().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.b().g().a().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.b().b().r().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.b().b().g().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.b().b().b().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.b().b().a().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.b().a().r().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.b().a().g().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.b().a().b().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.b().a().a().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.a().r().r().get(), new BVector3.Primitive(false, true, true));
    assertEquals(vec.a().r().g().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.a().r().b().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.a().r().a().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.a().g().r().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.a().g().g().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.a().g().b().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.a().g().a().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.a().b().r().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.a().b().g().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.a().b().b().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.a().b().a().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.a().a().r().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.a().a().g().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.a().a().b().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.a().a().a().get(), new BVector3.Primitive(false, false, false));

    assertEquals(vec.r().r().r().r(), new BVector4.Primitive(true, true, true, true));
    assertEquals(vec.r().r().r().g(), new BVector4.Primitive(true, true, true, false));
    assertEquals(vec.r().r().r().b(), new BVector4.Primitive(true, true, true, false));
    assertEquals(vec.r().r().r().a(), new BVector4.Primitive(true, true, true, false));
    assertEquals(vec.r().r().g().r(), new BVector4.Primitive(true, true, false, true));
    assertEquals(vec.r().r().g().g(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.r().r().g().b(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.r().r().g().a(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.r().r().b().r(), new BVector4.Primitive(true, true, false, true));
    assertEquals(vec.r().r().b().g(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.r().r().b().b(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.r().r().b().a(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.r().r().a().r(), new BVector4.Primitive(true, true, false, true));
    assertEquals(vec.r().r().a().g(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.r().r().a().b(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.r().r().a().a(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.r().g().r().r(), new BVector4.Primitive(true, false, true, true));
    assertEquals(vec.r().g().r().g(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.r().g().r().b(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.r().g().r().a(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.r().g().g().r(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.r().g().g().g(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().g().g().b(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().g().g().a(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().g().b().r(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.r().g().b().g(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().g().b().b(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().g().b().a(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().g().a().r(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.r().g().a().g(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().g().a().b(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().g().a().a(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().b().r().r(), new BVector4.Primitive(true, false, true, true));
    assertEquals(vec.r().b().r().g(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.r().b().r().b(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.r().b().r().a(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.r().b().g().r(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.r().b().g().g(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().b().g().b(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().b().g().a(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().b().b().r(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.r().b().b().g(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().b().b().b(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().b().b().a(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().b().a().r(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.r().b().a().g(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().b().a().b(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().b().a().a(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().a().r().r(), new BVector4.Primitive(true, false, true, true));
    assertEquals(vec.r().a().r().g(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.r().a().r().b(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.r().a().r().a(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.r().a().g().r(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.r().a().g().g(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().a().g().b(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().a().g().a(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().a().b().r(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.r().a().b().g(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().a().b().b(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().a().b().a(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().a().a().r(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.r().a().a().g(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().a().a().b(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.r().a().a().a(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.g().r().r().r(), new BVector4.Primitive(false, true, true, true));
    assertEquals(vec.g().r().r().g(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.g().r().r().b(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.g().r().r().a(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.g().r().g().r(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.g().r().g().g(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.g().r().g().b(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.g().r().g().a(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.g().r().b().r(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.g().r().b().g(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.g().r().b().b(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.g().r().b().a(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.g().r().a().r(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.g().r().a().g(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.g().r().a().b(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.g().r().a().a(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.g().g().r().r(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.g().g().r().g(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.g().g().r().b(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.g().g().r().a(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.g().g().g().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.g().g().g().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().g().g().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().g().g().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().g().b().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.g().g().b().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().g().b().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().g().b().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().g().a().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.g().g().a().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().g().a().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().g().a().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().b().r().r(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.g().b().r().g(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.g().b().r().b(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.g().b().r().a(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.g().b().g().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.g().b().g().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().b().g().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().b().g().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().b().b().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.g().b().b().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().b().b().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().b().b().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().b().a().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.g().b().a().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().b().a().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().b().a().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().a().r().r(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.g().a().r().g(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.g().a().r().b(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.g().a().r().a(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.g().a().g().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.g().a().g().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().a().g().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().a().g().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().a().b().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.g().a().b().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().a().b().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().a().b().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().a().a().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.g().a().a().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().a().a().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.g().a().a().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().r().r().r(), new BVector4.Primitive(false, true, true, true));
    assertEquals(vec.b().r().r().g(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.b().r().r().b(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.b().r().r().a(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.b().r().g().r(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.b().r().g().g(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.b().r().g().b(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.b().r().g().a(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.b().r().b().r(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.b().r().b().g(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.b().r().b().b(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.b().r().b().a(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.b().r().a().r(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.b().r().a().g(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.b().r().a().b(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.b().r().a().a(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.b().g().r().r(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.b().g().r().g(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.b().g().r().b(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.b().g().r().a(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.b().g().g().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.b().g().g().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().g().g().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().g().g().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().g().b().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.b().g().b().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().g().b().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().g().b().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().g().a().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.b().g().a().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().g().a().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().g().a().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().b().r().r(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.b().b().r().g(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.b().b().r().b(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.b().b().r().a(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.b().b().g().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.b().b().g().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().b().g().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().b().g().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().b().b().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.b().b().b().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().b().b().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().b().b().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().b().a().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.b().b().a().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().b().a().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().b().a().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().a().r().r(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.b().a().r().g(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.b().a().r().b(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.b().a().r().a(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.b().a().g().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.b().a().g().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().a().g().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().a().g().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().a().b().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.b().a().b().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().a().b().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().a().b().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().a().a().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.b().a().a().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().a().a().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.b().a().a().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().r().r().r(), new BVector4.Primitive(false, true, true, true));
    assertEquals(vec.a().r().r().g(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.a().r().r().b(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.a().r().r().a(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.a().r().g().r(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.a().r().g().g(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.a().r().g().b(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.a().r().g().a(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.a().r().b().r(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.a().r().b().g(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.a().r().b().b(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.a().r().b().a(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.a().r().a().r(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.a().r().a().g(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.a().r().a().b(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.a().r().a().a(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.a().g().r().r(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.a().g().r().g(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.a().g().r().b(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.a().g().r().a(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.a().g().g().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.a().g().g().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().g().g().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().g().g().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().g().b().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.a().g().b().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().g().b().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().g().b().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().g().a().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.a().g().a().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().g().a().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().g().a().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().b().r().r(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.a().b().r().g(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.a().b().r().b(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.a().b().r().a(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.a().b().g().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.a().b().g().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().b().g().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().b().g().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().b().b().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.a().b().b().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().b().b().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().b().b().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().b().a().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.a().b().a().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().b().a().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().b().a().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().a().r().r(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.a().a().r().g(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.a().a().r().b(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.a().a().r().a(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.a().a().g().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.a().a().g().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().a().g().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().a().g().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().a().b().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.a().a().b().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().a().b().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().a().b().a(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().a().a().r(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.a().a().a().g(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().a().a().b(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.a().a().a().a(), new BVector4.Primitive(false, false, false, false));

  }

  @Test
  @SuppressWarnings("all")
  public void testSwizzleSTPQ() {
    assertTrue(vec.s().get() == true);
    assertTrue(vec.t().get() == false);
    assertTrue(vec.p().get() == false);
    assertTrue(vec.q().get() == false);

    assertEquals(vec.s().s().get(), new BVector2.Primitive(true, true));
    assertEquals(vec.s().t().get(), new BVector2.Primitive(true, false));
    assertEquals(vec.s().p().get(), new BVector2.Primitive(true, false));
    assertEquals(vec.s().q().get(), new BVector2.Primitive(true, false));
    assertEquals(vec.t().s().get(), new BVector2.Primitive(false, true));
    assertEquals(vec.t().t().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.t().p().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.t().q().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.p().s().get(), new BVector2.Primitive(false, true));
    assertEquals(vec.p().t().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.p().p().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.p().q().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.q().s().get(), new BVector2.Primitive(false, true));
    assertEquals(vec.q().t().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.q().p().get(), new BVector2.Primitive(false, false));
    assertEquals(vec.q().q().get(), new BVector2.Primitive(false, false));

    assertEquals(vec.s().s().s().get(), new BVector3.Primitive(true, true, true));
    assertEquals(vec.s().s().t().get(), new BVector3.Primitive(true, true, false));
    assertEquals(vec.s().s().p().get(), new BVector3.Primitive(true, true, false));
    assertEquals(vec.s().s().q().get(), new BVector3.Primitive(true, true, false));
    assertEquals(vec.s().t().s().get(), new BVector3.Primitive(true, false, true));
    assertEquals(vec.s().t().t().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.s().t().p().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.s().t().q().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.s().p().s().get(), new BVector3.Primitive(true, false, true));
    assertEquals(vec.s().p().t().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.s().p().p().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.s().p().q().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.s().q().s().get(), new BVector3.Primitive(true, false, true));
    assertEquals(vec.s().q().t().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.s().q().p().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.s().q().q().get(), new BVector3.Primitive(true, false, false));
    assertEquals(vec.t().s().s().get(), new BVector3.Primitive(false, true, true));
    assertEquals(vec.t().s().t().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.t().s().p().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.t().s().q().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.t().t().s().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.t().t().t().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.t().t().p().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.t().t().q().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.t().p().s().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.t().p().t().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.t().p().p().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.t().p().q().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.t().q().s().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.t().q().t().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.t().q().p().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.t().q().q().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.p().s().s().get(), new BVector3.Primitive(false, true, true));
    assertEquals(vec.p().s().t().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.p().s().p().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.p().s().q().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.p().t().s().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.p().t().t().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.p().t().p().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.p().t().q().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.p().p().s().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.p().p().t().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.p().p().p().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.p().p().q().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.p().q().s().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.p().q().t().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.p().q().p().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.p().q().q().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.q().s().s().get(), new BVector3.Primitive(false, true, true));
    assertEquals(vec.q().s().t().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.q().s().p().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.q().s().q().get(), new BVector3.Primitive(false, true, false));
    assertEquals(vec.q().t().s().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.q().t().t().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.q().t().p().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.q().t().q().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.q().p().s().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.q().p().t().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.q().p().p().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.q().p().q().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.q().q().s().get(), new BVector3.Primitive(false, false, true));
    assertEquals(vec.q().q().t().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.q().q().p().get(), new BVector3.Primitive(false, false, false));
    assertEquals(vec.q().q().q().get(), new BVector3.Primitive(false, false, false));

    assertEquals(vec.s().s().s().s(), new BVector4.Primitive(true, true, true, true));
    assertEquals(vec.s().s().s().t(), new BVector4.Primitive(true, true, true, false));
    assertEquals(vec.s().s().s().p(), new BVector4.Primitive(true, true, true, false));
    assertEquals(vec.s().s().s().q(), new BVector4.Primitive(true, true, true, false));
    assertEquals(vec.s().s().t().s(), new BVector4.Primitive(true, true, false, true));
    assertEquals(vec.s().s().t().t(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.s().s().t().p(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.s().s().t().q(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.s().s().p().s(), new BVector4.Primitive(true, true, false, true));
    assertEquals(vec.s().s().p().t(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.s().s().p().p(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.s().s().p().q(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.s().s().q().s(), new BVector4.Primitive(true, true, false, true));
    assertEquals(vec.s().s().q().t(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.s().s().q().p(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.s().s().q().q(), new BVector4.Primitive(true, true, false, false));
    assertEquals(vec.s().t().s().s(), new BVector4.Primitive(true, false, true, true));
    assertEquals(vec.s().t().s().t(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.s().t().s().p(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.s().t().s().q(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.s().t().t().s(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.s().t().t().t(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().t().t().p(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().t().t().q(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().t().p().s(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.s().t().p().t(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().t().p().p(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().t().p().q(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().t().q().s(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.s().t().q().t(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().t().q().p(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().t().q().q(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().p().s().s(), new BVector4.Primitive(true, false, true, true));
    assertEquals(vec.s().p().s().t(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.s().p().s().p(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.s().p().s().q(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.s().p().t().s(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.s().p().t().t(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().p().t().p(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().p().t().q(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().p().p().s(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.s().p().p().t(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().p().p().p(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().p().p().q(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().p().q().s(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.s().p().q().t(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().p().q().p(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().p().q().q(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().q().s().s(), new BVector4.Primitive(true, false, true, true));
    assertEquals(vec.s().q().s().t(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.s().q().s().p(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.s().q().s().q(), new BVector4.Primitive(true, false, true, false));
    assertEquals(vec.s().q().t().s(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.s().q().t().t(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().q().t().p(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().q().t().q(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().q().p().s(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.s().q().p().t(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().q().p().p(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().q().p().q(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().q().q().s(), new BVector4.Primitive(true, false, false, true));
    assertEquals(vec.s().q().q().t(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().q().q().p(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.s().q().q().q(), new BVector4.Primitive(true, false, false, false));
    assertEquals(vec.t().s().s().s(), new BVector4.Primitive(false, true, true, true));
    assertEquals(vec.t().s().s().t(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.t().s().s().p(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.t().s().s().q(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.t().s().t().s(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.t().s().t().t(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.t().s().t().p(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.t().s().t().q(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.t().s().p().s(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.t().s().p().t(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.t().s().p().p(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.t().s().p().q(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.t().s().q().s(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.t().s().q().t(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.t().s().q().p(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.t().s().q().q(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.t().t().s().s(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.t().t().s().t(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.t().t().s().p(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.t().t().s().q(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.t().t().t().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.t().t().t().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().t().t().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().t().t().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().t().p().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.t().t().p().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().t().p().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().t().p().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().t().q().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.t().t().q().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().t().q().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().t().q().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().p().s().s(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.t().p().s().t(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.t().p().s().p(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.t().p().s().q(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.t().p().t().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.t().p().t().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().p().t().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().p().t().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().p().p().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.t().p().p().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().p().p().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().p().p().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().p().q().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.t().p().q().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().p().q().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().p().q().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().q().s().s(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.t().q().s().t(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.t().q().s().p(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.t().q().s().q(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.t().q().t().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.t().q().t().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().q().t().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().q().t().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().q().p().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.t().q().p().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().q().p().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().q().p().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().q().q().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.t().q().q().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().q().q().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.t().q().q().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().s().s().s(), new BVector4.Primitive(false, true, true, true));
    assertEquals(vec.p().s().s().t(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.p().s().s().p(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.p().s().s().q(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.p().s().t().s(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.p().s().t().t(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.p().s().t().p(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.p().s().t().q(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.p().s().p().s(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.p().s().p().t(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.p().s().p().p(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.p().s().p().q(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.p().s().q().s(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.p().s().q().t(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.p().s().q().p(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.p().s().q().q(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.p().t().s().s(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.p().t().s().t(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.p().t().s().p(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.p().t().s().q(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.p().t().t().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.p().t().t().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().t().t().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().t().t().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().t().p().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.p().t().p().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().t().p().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().t().p().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().t().q().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.p().t().q().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().t().q().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().t().q().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().p().s().s(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.p().p().s().t(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.p().p().s().p(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.p().p().s().q(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.p().p().t().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.p().p().t().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().p().t().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().p().t().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().p().p().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.p().p().p().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().p().p().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().p().p().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().p().q().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.p().p().q().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().p().q().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().p().q().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().q().s().s(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.p().q().s().t(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.p().q().s().p(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.p().q().s().q(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.p().q().t().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.p().q().t().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().q().t().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().q().t().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().q().p().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.p().q().p().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().q().p().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().q().p().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().q().q().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.p().q().q().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().q().q().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.p().q().q().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().s().s().s(), new BVector4.Primitive(false, true, true, true));
    assertEquals(vec.q().s().s().t(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.q().s().s().p(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.q().s().s().q(), new BVector4.Primitive(false, true, true, false));
    assertEquals(vec.q().s().t().s(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.q().s().t().t(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.q().s().t().p(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.q().s().t().q(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.q().s().p().s(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.q().s().p().t(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.q().s().p().p(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.q().s().p().q(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.q().s().q().s(), new BVector4.Primitive(false, true, false, true));
    assertEquals(vec.q().s().q().t(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.q().s().q().p(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.q().s().q().q(), new BVector4.Primitive(false, true, false, false));
    assertEquals(vec.q().t().s().s(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.q().t().s().t(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.q().t().s().p(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.q().t().s().q(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.q().t().t().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.q().t().t().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().t().t().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().t().t().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().t().p().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.q().t().p().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().t().p().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().t().p().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().t().q().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.q().t().q().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().t().q().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().t().q().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().p().s().s(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.q().p().s().t(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.q().p().s().p(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.q().p().s().q(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.q().p().t().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.q().p().t().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().p().t().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().p().t().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().p().p().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.q().p().p().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().p().p().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().p().p().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().p().q().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.q().p().q().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().p().q().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().p().q().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().q().s().s(), new BVector4.Primitive(false, false, true, true));
    assertEquals(vec.q().q().s().t(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.q().q().s().p(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.q().q().s().q(), new BVector4.Primitive(false, false, true, false));
    assertEquals(vec.q().q().t().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.q().q().t().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().q().t().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().q().t().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().q().p().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.q().q().p().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().q().p().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().q().p().q(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().q().q().s(), new BVector4.Primitive(false, false, false, true));
    assertEquals(vec.q().q().q().t(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().q().q().p(), new BVector4.Primitive(false, false, false, false));
    assertEquals(vec.q().q().q().q(), new BVector4.Primitive(false, false, false, false));

  }

  @Test
  public void testAny() {
    assertTrue(vec.any());

    BVector4.Primitive other = new BVector4.Primitive(false, false, false, false);
    assertFalse(other.any());
  }

  @Test
  public void testAll() {
    assertFalse(vec.all());

    BVector4.Primitive other = new BVector4.Primitive(true, true, true, true);
    assertTrue(other.all());
  }

  @Test
  public void testNot() {
    BVector4.Primitive not = vec.not();

    assertFalse(not.getX());
    assertTrue(not.getY());
    assertTrue(not.getZ());
    assertTrue(not.getW());
  }

  @Test
  @SuppressWarnings("all")
  public void testEquals() {
    BVector4.Primitive equal = new BVector4.Primitive(true, false, false, false);
    assertEquals(vec, equal);

    BVector4.Primitive unequal = new BVector4.Primitive(false, false, false, false);
    assertFalse(vec.equals(unequal));

    assertFalse(vec.equals(null));

    assertFalse(vec.equals("A string"));
  }

  @Test
  public void testHashCode() {
    BVector4.Primitive equal = new BVector4.Primitive(true, false, false, false);

    assertEquals(vec, equal);
    assertEquals(vec.hashCode(), equal.hashCode());
  }

  @Test
  public void testToString() {
    String toString = vec.toString();
    assertEquals(toString, "bvec4(true, false, false, false)");
  }
}
