package com.lfscheidegger.jfacet.shade.expression.vector;

import org.junit.Test;

import static org.junit.Assert.*;
/**
 * Unit tests for {@code Vector4.Primitive}
 */
public class Vector4PrimitiveTest {

  private final Vector4.Primitive vec;

  public Vector4PrimitiveTest() {
    vec = new Vector4.Primitive(1, 2, 3, 4);
  }

  @Test
  public void testConstructors() {
    assertTrue(vec.getX() == 1);
    assertTrue(vec.getY() == 2);
    assertTrue(vec.getZ() == 3);
    assertTrue(vec.getW() == 4);
  }

  @Test
  public void testGetters() {
    float x = vec.getX();
    float y = vec.getY();
    float z = vec.getZ();
    float w = vec.getW();

    assertTrue(x == 1);
    assertTrue(y == 2);
    assertTrue(z == 3);
    assertTrue(w == 4);

    assertTrue(vec.get(0) == vec.getX());
    assertTrue(vec.get(1) == vec.getY());
    assertTrue(vec.get(2) == vec.getZ());
    assertTrue(vec.get(3) == vec.getW());
  }

  @Test
  @SuppressWarnings("all")
  public void testSwizzleXYZW() {
    assertTrue(vec.x().get() == 1);
    assertTrue(vec.y().get() == 2);
    assertTrue(vec.z().get() == 3);
    assertTrue(vec.w().get() == 4);

    assertEquals(vec.x().x().get(), new Vector2.Primitive(1, 1));
    assertEquals(vec.x().y().get(), new Vector2.Primitive(1, 2));
    assertEquals(vec.x().z().get(), new Vector2.Primitive(1, 3));
    assertEquals(vec.x().w().get(), new Vector2.Primitive(1, 4));
    assertEquals(vec.y().x().get(), new Vector2.Primitive(2, 1));
    assertEquals(vec.y().y().get(), new Vector2.Primitive(2, 2));
    assertEquals(vec.y().z().get(), new Vector2.Primitive(2, 3));
    assertEquals(vec.y().w().get(), new Vector2.Primitive(2, 4));
    assertEquals(vec.z().x().get(), new Vector2.Primitive(3, 1));
    assertEquals(vec.z().y().get(), new Vector2.Primitive(3, 2));
    assertEquals(vec.z().z().get(), new Vector2.Primitive(3, 3));
    assertEquals(vec.z().w().get(), new Vector2.Primitive(3, 4));
    assertEquals(vec.w().x().get(), new Vector2.Primitive(4, 1));
    assertEquals(vec.w().y().get(), new Vector2.Primitive(4, 2));
    assertEquals(vec.w().z().get(), new Vector2.Primitive(4, 3));
    assertEquals(vec.w().w().get(), new Vector2.Primitive(4, 4));

    assertEquals(vec.x().x().x().get(), new Vector3.Primitive(1, 1, 1));
    assertEquals(vec.x().x().y().get(), new Vector3.Primitive(1, 1, 2));
    assertEquals(vec.x().x().z().get(), new Vector3.Primitive(1, 1, 3));
    assertEquals(vec.x().x().w().get(), new Vector3.Primitive(1, 1, 4));
    assertEquals(vec.x().y().x().get(), new Vector3.Primitive(1, 2, 1));
    assertEquals(vec.x().y().y().get(), new Vector3.Primitive(1, 2, 2));
    assertEquals(vec.x().y().z().get(), new Vector3.Primitive(1, 2, 3));
    assertEquals(vec.x().y().w().get(), new Vector3.Primitive(1, 2, 4));
    assertEquals(vec.x().z().x().get(), new Vector3.Primitive(1, 3, 1));
    assertEquals(vec.x().z().y().get(), new Vector3.Primitive(1, 3, 2));
    assertEquals(vec.x().z().z().get(), new Vector3.Primitive(1, 3, 3));
    assertEquals(vec.x().z().w().get(), new Vector3.Primitive(1, 3, 4));
    assertEquals(vec.x().w().x().get(), new Vector3.Primitive(1, 4, 1));
    assertEquals(vec.x().w().y().get(), new Vector3.Primitive(1, 4, 2));
    assertEquals(vec.x().w().z().get(), new Vector3.Primitive(1, 4, 3));
    assertEquals(vec.x().w().w().get(), new Vector3.Primitive(1, 4, 4));
    assertEquals(vec.y().x().x().get(), new Vector3.Primitive(2, 1, 1));
    assertEquals(vec.y().x().y().get(), new Vector3.Primitive(2, 1, 2));
    assertEquals(vec.y().x().z().get(), new Vector3.Primitive(2, 1, 3));
    assertEquals(vec.y().x().w().get(), new Vector3.Primitive(2, 1, 4));
    assertEquals(vec.y().y().x().get(), new Vector3.Primitive(2, 2, 1));
    assertEquals(vec.y().y().y().get(), new Vector3.Primitive(2, 2, 2));
    assertEquals(vec.y().y().z().get(), new Vector3.Primitive(2, 2, 3));
    assertEquals(vec.y().y().w().get(), new Vector3.Primitive(2, 2, 4));
    assertEquals(vec.y().z().x().get(), new Vector3.Primitive(2, 3, 1));
    assertEquals(vec.y().z().y().get(), new Vector3.Primitive(2, 3, 2));
    assertEquals(vec.y().z().z().get(), new Vector3.Primitive(2, 3, 3));
    assertEquals(vec.y().z().w().get(), new Vector3.Primitive(2, 3, 4));
    assertEquals(vec.y().w().x().get(), new Vector3.Primitive(2, 4, 1));
    assertEquals(vec.y().w().y().get(), new Vector3.Primitive(2, 4, 2));
    assertEquals(vec.y().w().z().get(), new Vector3.Primitive(2, 4, 3));
    assertEquals(vec.y().w().w().get(), new Vector3.Primitive(2, 4, 4));
    assertEquals(vec.z().x().x().get(), new Vector3.Primitive(3, 1, 1));
    assertEquals(vec.z().x().y().get(), new Vector3.Primitive(3, 1, 2));
    assertEquals(vec.z().x().z().get(), new Vector3.Primitive(3, 1, 3));
    assertEquals(vec.z().x().w().get(), new Vector3.Primitive(3, 1, 4));
    assertEquals(vec.z().y().x().get(), new Vector3.Primitive(3, 2, 1));
    assertEquals(vec.z().y().y().get(), new Vector3.Primitive(3, 2, 2));
    assertEquals(vec.z().y().z().get(), new Vector3.Primitive(3, 2, 3));
    assertEquals(vec.z().y().w().get(), new Vector3.Primitive(3, 2, 4));
    assertEquals(vec.z().z().x().get(), new Vector3.Primitive(3, 3, 1));
    assertEquals(vec.z().z().y().get(), new Vector3.Primitive(3, 3, 2));
    assertEquals(vec.z().z().z().get(), new Vector3.Primitive(3, 3, 3));
    assertEquals(vec.z().z().w().get(), new Vector3.Primitive(3, 3, 4));
    assertEquals(vec.z().w().x().get(), new Vector3.Primitive(3, 4, 1));
    assertEquals(vec.z().w().y().get(), new Vector3.Primitive(3, 4, 2));
    assertEquals(vec.z().w().z().get(), new Vector3.Primitive(3, 4, 3));
    assertEquals(vec.z().w().w().get(), new Vector3.Primitive(3, 4, 4));
    assertEquals(vec.w().x().x().get(), new Vector3.Primitive(4, 1, 1));
    assertEquals(vec.w().x().y().get(), new Vector3.Primitive(4, 1, 2));
    assertEquals(vec.w().x().z().get(), new Vector3.Primitive(4, 1, 3));
    assertEquals(vec.w().x().w().get(), new Vector3.Primitive(4, 1, 4));
    assertEquals(vec.w().y().x().get(), new Vector3.Primitive(4, 2, 1));
    assertEquals(vec.w().y().y().get(), new Vector3.Primitive(4, 2, 2));
    assertEquals(vec.w().y().z().get(), new Vector3.Primitive(4, 2, 3));
    assertEquals(vec.w().y().w().get(), new Vector3.Primitive(4, 2, 4));
    assertEquals(vec.w().z().x().get(), new Vector3.Primitive(4, 3, 1));
    assertEquals(vec.w().z().y().get(), new Vector3.Primitive(4, 3, 2));
    assertEquals(vec.w().z().z().get(), new Vector3.Primitive(4, 3, 3));
    assertEquals(vec.w().z().w().get(), new Vector3.Primitive(4, 3, 4));
    assertEquals(vec.w().w().x().get(), new Vector3.Primitive(4, 4, 1));
    assertEquals(vec.w().w().y().get(), new Vector3.Primitive(4, 4, 2));
    assertEquals(vec.w().w().z().get(), new Vector3.Primitive(4, 4, 3));
    assertEquals(vec.w().w().w().get(), new Vector3.Primitive(4, 4, 4));

    assertEquals(vec.x().x().x().x(), new Vector4.Primitive(1, 1, 1, 1));
    assertEquals(vec.x().x().x().y(), new Vector4.Primitive(1, 1, 1, 2));
    assertEquals(vec.x().x().x().z(), new Vector4.Primitive(1, 1, 1, 3));
    assertEquals(vec.x().x().x().w(), new Vector4.Primitive(1, 1, 1, 4));
    assertEquals(vec.x().x().y().x(), new Vector4.Primitive(1, 1, 2, 1));
    assertEquals(vec.x().x().y().y(), new Vector4.Primitive(1, 1, 2, 2));
    assertEquals(vec.x().x().y().z(), new Vector4.Primitive(1, 1, 2, 3));
    assertEquals(vec.x().x().y().w(), new Vector4.Primitive(1, 1, 2, 4));
    assertEquals(vec.x().x().z().x(), new Vector4.Primitive(1, 1, 3, 1));
    assertEquals(vec.x().x().z().y(), new Vector4.Primitive(1, 1, 3, 2));
    assertEquals(vec.x().x().z().z(), new Vector4.Primitive(1, 1, 3, 3));
    assertEquals(vec.x().x().z().w(), new Vector4.Primitive(1, 1, 3, 4));
    assertEquals(vec.x().x().w().x(), new Vector4.Primitive(1, 1, 4, 1));
    assertEquals(vec.x().x().w().y(), new Vector4.Primitive(1, 1, 4, 2));
    assertEquals(vec.x().x().w().z(), new Vector4.Primitive(1, 1, 4, 3));
    assertEquals(vec.x().x().w().w(), new Vector4.Primitive(1, 1, 4, 4));
    assertEquals(vec.x().y().x().x(), new Vector4.Primitive(1, 2, 1, 1));
    assertEquals(vec.x().y().x().y(), new Vector4.Primitive(1, 2, 1, 2));
    assertEquals(vec.x().y().x().z(), new Vector4.Primitive(1, 2, 1, 3));
    assertEquals(vec.x().y().x().w(), new Vector4.Primitive(1, 2, 1, 4));
    assertEquals(vec.x().y().y().x(), new Vector4.Primitive(1, 2, 2, 1));
    assertEquals(vec.x().y().y().y(), new Vector4.Primitive(1, 2, 2, 2));
    assertEquals(vec.x().y().y().z(), new Vector4.Primitive(1, 2, 2, 3));
    assertEquals(vec.x().y().y().w(), new Vector4.Primitive(1, 2, 2, 4));
    assertEquals(vec.x().y().z().x(), new Vector4.Primitive(1, 2, 3, 1));
    assertEquals(vec.x().y().z().y(), new Vector4.Primitive(1, 2, 3, 2));
    assertEquals(vec.x().y().z().z(), new Vector4.Primitive(1, 2, 3, 3));
    assertEquals(vec.x().y().z().w(), new Vector4.Primitive(1, 2, 3, 4));
    assertEquals(vec.x().y().w().x(), new Vector4.Primitive(1, 2, 4, 1));
    assertEquals(vec.x().y().w().y(), new Vector4.Primitive(1, 2, 4, 2));
    assertEquals(vec.x().y().w().z(), new Vector4.Primitive(1, 2, 4, 3));
    assertEquals(vec.x().y().w().w(), new Vector4.Primitive(1, 2, 4, 4));
    assertEquals(vec.x().z().x().x(), new Vector4.Primitive(1, 3, 1, 1));
    assertEquals(vec.x().z().x().y(), new Vector4.Primitive(1, 3, 1, 2));
    assertEquals(vec.x().z().x().z(), new Vector4.Primitive(1, 3, 1, 3));
    assertEquals(vec.x().z().x().w(), new Vector4.Primitive(1, 3, 1, 4));
    assertEquals(vec.x().z().y().x(), new Vector4.Primitive(1, 3, 2, 1));
    assertEquals(vec.x().z().y().y(), new Vector4.Primitive(1, 3, 2, 2));
    assertEquals(vec.x().z().y().z(), new Vector4.Primitive(1, 3, 2, 3));
    assertEquals(vec.x().z().y().w(), new Vector4.Primitive(1, 3, 2, 4));
    assertEquals(vec.x().z().z().x(), new Vector4.Primitive(1, 3, 3, 1));
    assertEquals(vec.x().z().z().y(), new Vector4.Primitive(1, 3, 3, 2));
    assertEquals(vec.x().z().z().z(), new Vector4.Primitive(1, 3, 3, 3));
    assertEquals(vec.x().z().z().w(), new Vector4.Primitive(1, 3, 3, 4));
    assertEquals(vec.x().z().w().x(), new Vector4.Primitive(1, 3, 4, 1));
    assertEquals(vec.x().z().w().y(), new Vector4.Primitive(1, 3, 4, 2));
    assertEquals(vec.x().z().w().z(), new Vector4.Primitive(1, 3, 4, 3));
    assertEquals(vec.x().z().w().w(), new Vector4.Primitive(1, 3, 4, 4));
    assertEquals(vec.x().w().x().x(), new Vector4.Primitive(1, 4, 1, 1));
    assertEquals(vec.x().w().x().y(), new Vector4.Primitive(1, 4, 1, 2));
    assertEquals(vec.x().w().x().z(), new Vector4.Primitive(1, 4, 1, 3));
    assertEquals(vec.x().w().x().w(), new Vector4.Primitive(1, 4, 1, 4));
    assertEquals(vec.x().w().y().x(), new Vector4.Primitive(1, 4, 2, 1));
    assertEquals(vec.x().w().y().y(), new Vector4.Primitive(1, 4, 2, 2));
    assertEquals(vec.x().w().y().z(), new Vector4.Primitive(1, 4, 2, 3));
    assertEquals(vec.x().w().y().w(), new Vector4.Primitive(1, 4, 2, 4));
    assertEquals(vec.x().w().z().x(), new Vector4.Primitive(1, 4, 3, 1));
    assertEquals(vec.x().w().z().y(), new Vector4.Primitive(1, 4, 3, 2));
    assertEquals(vec.x().w().z().z(), new Vector4.Primitive(1, 4, 3, 3));
    assertEquals(vec.x().w().z().w(), new Vector4.Primitive(1, 4, 3, 4));
    assertEquals(vec.x().w().w().x(), new Vector4.Primitive(1, 4, 4, 1));
    assertEquals(vec.x().w().w().y(), new Vector4.Primitive(1, 4, 4, 2));
    assertEquals(vec.x().w().w().z(), new Vector4.Primitive(1, 4, 4, 3));
    assertEquals(vec.x().w().w().w(), new Vector4.Primitive(1, 4, 4, 4));
    assertEquals(vec.y().x().x().x(), new Vector4.Primitive(2, 1, 1, 1));
    assertEquals(vec.y().x().x().y(), new Vector4.Primitive(2, 1, 1, 2));
    assertEquals(vec.y().x().x().z(), new Vector4.Primitive(2, 1, 1, 3));
    assertEquals(vec.y().x().x().w(), new Vector4.Primitive(2, 1, 1, 4));
    assertEquals(vec.y().x().y().x(), new Vector4.Primitive(2, 1, 2, 1));
    assertEquals(vec.y().x().y().y(), new Vector4.Primitive(2, 1, 2, 2));
    assertEquals(vec.y().x().y().z(), new Vector4.Primitive(2, 1, 2, 3));
    assertEquals(vec.y().x().y().w(), new Vector4.Primitive(2, 1, 2, 4));
    assertEquals(vec.y().x().z().x(), new Vector4.Primitive(2, 1, 3, 1));
    assertEquals(vec.y().x().z().y(), new Vector4.Primitive(2, 1, 3, 2));
    assertEquals(vec.y().x().z().z(), new Vector4.Primitive(2, 1, 3, 3));
    assertEquals(vec.y().x().z().w(), new Vector4.Primitive(2, 1, 3, 4));
    assertEquals(vec.y().x().w().x(), new Vector4.Primitive(2, 1, 4, 1));
    assertEquals(vec.y().x().w().y(), new Vector4.Primitive(2, 1, 4, 2));
    assertEquals(vec.y().x().w().z(), new Vector4.Primitive(2, 1, 4, 3));
    assertEquals(vec.y().x().w().w(), new Vector4.Primitive(2, 1, 4, 4));
    assertEquals(vec.y().y().x().x(), new Vector4.Primitive(2, 2, 1, 1));
    assertEquals(vec.y().y().x().y(), new Vector4.Primitive(2, 2, 1, 2));
    assertEquals(vec.y().y().x().z(), new Vector4.Primitive(2, 2, 1, 3));
    assertEquals(vec.y().y().x().w(), new Vector4.Primitive(2, 2, 1, 4));
    assertEquals(vec.y().y().y().x(), new Vector4.Primitive(2, 2, 2, 1));
    assertEquals(vec.y().y().y().y(), new Vector4.Primitive(2, 2, 2, 2));
    assertEquals(vec.y().y().y().z(), new Vector4.Primitive(2, 2, 2, 3));
    assertEquals(vec.y().y().y().w(), new Vector4.Primitive(2, 2, 2, 4));
    assertEquals(vec.y().y().z().x(), new Vector4.Primitive(2, 2, 3, 1));
    assertEquals(vec.y().y().z().y(), new Vector4.Primitive(2, 2, 3, 2));
    assertEquals(vec.y().y().z().z(), new Vector4.Primitive(2, 2, 3, 3));
    assertEquals(vec.y().y().z().w(), new Vector4.Primitive(2, 2, 3, 4));
    assertEquals(vec.y().y().w().x(), new Vector4.Primitive(2, 2, 4, 1));
    assertEquals(vec.y().y().w().y(), new Vector4.Primitive(2, 2, 4, 2));
    assertEquals(vec.y().y().w().z(), new Vector4.Primitive(2, 2, 4, 3));
    assertEquals(vec.y().y().w().w(), new Vector4.Primitive(2, 2, 4, 4));
    assertEquals(vec.y().z().x().x(), new Vector4.Primitive(2, 3, 1, 1));
    assertEquals(vec.y().z().x().y(), new Vector4.Primitive(2, 3, 1, 2));
    assertEquals(vec.y().z().x().z(), new Vector4.Primitive(2, 3, 1, 3));
    assertEquals(vec.y().z().x().w(), new Vector4.Primitive(2, 3, 1, 4));
    assertEquals(vec.y().z().y().x(), new Vector4.Primitive(2, 3, 2, 1));
    assertEquals(vec.y().z().y().y(), new Vector4.Primitive(2, 3, 2, 2));
    assertEquals(vec.y().z().y().z(), new Vector4.Primitive(2, 3, 2, 3));
    assertEquals(vec.y().z().y().w(), new Vector4.Primitive(2, 3, 2, 4));
    assertEquals(vec.y().z().z().x(), new Vector4.Primitive(2, 3, 3, 1));
    assertEquals(vec.y().z().z().y(), new Vector4.Primitive(2, 3, 3, 2));
    assertEquals(vec.y().z().z().z(), new Vector4.Primitive(2, 3, 3, 3));
    assertEquals(vec.y().z().z().w(), new Vector4.Primitive(2, 3, 3, 4));
    assertEquals(vec.y().z().w().x(), new Vector4.Primitive(2, 3, 4, 1));
    assertEquals(vec.y().z().w().y(), new Vector4.Primitive(2, 3, 4, 2));
    assertEquals(vec.y().z().w().z(), new Vector4.Primitive(2, 3, 4, 3));
    assertEquals(vec.y().z().w().w(), new Vector4.Primitive(2, 3, 4, 4));
    assertEquals(vec.y().w().x().x(), new Vector4.Primitive(2, 4, 1, 1));
    assertEquals(vec.y().w().x().y(), new Vector4.Primitive(2, 4, 1, 2));
    assertEquals(vec.y().w().x().z(), new Vector4.Primitive(2, 4, 1, 3));
    assertEquals(vec.y().w().x().w(), new Vector4.Primitive(2, 4, 1, 4));
    assertEquals(vec.y().w().y().x(), new Vector4.Primitive(2, 4, 2, 1));
    assertEquals(vec.y().w().y().y(), new Vector4.Primitive(2, 4, 2, 2));
    assertEquals(vec.y().w().y().z(), new Vector4.Primitive(2, 4, 2, 3));
    assertEquals(vec.y().w().y().w(), new Vector4.Primitive(2, 4, 2, 4));
    assertEquals(vec.y().w().z().x(), new Vector4.Primitive(2, 4, 3, 1));
    assertEquals(vec.y().w().z().y(), new Vector4.Primitive(2, 4, 3, 2));
    assertEquals(vec.y().w().z().z(), new Vector4.Primitive(2, 4, 3, 3));
    assertEquals(vec.y().w().z().w(), new Vector4.Primitive(2, 4, 3, 4));
    assertEquals(vec.y().w().w().x(), new Vector4.Primitive(2, 4, 4, 1));
    assertEquals(vec.y().w().w().y(), new Vector4.Primitive(2, 4, 4, 2));
    assertEquals(vec.y().w().w().z(), new Vector4.Primitive(2, 4, 4, 3));
    assertEquals(vec.y().w().w().w(), new Vector4.Primitive(2, 4, 4, 4));
    assertEquals(vec.z().x().x().x(), new Vector4.Primitive(3, 1, 1, 1));
    assertEquals(vec.z().x().x().y(), new Vector4.Primitive(3, 1, 1, 2));
    assertEquals(vec.z().x().x().z(), new Vector4.Primitive(3, 1, 1, 3));
    assertEquals(vec.z().x().x().w(), new Vector4.Primitive(3, 1, 1, 4));
    assertEquals(vec.z().x().y().x(), new Vector4.Primitive(3, 1, 2, 1));
    assertEquals(vec.z().x().y().y(), new Vector4.Primitive(3, 1, 2, 2));
    assertEquals(vec.z().x().y().z(), new Vector4.Primitive(3, 1, 2, 3));
    assertEquals(vec.z().x().y().w(), new Vector4.Primitive(3, 1, 2, 4));
    assertEquals(vec.z().x().z().x(), new Vector4.Primitive(3, 1, 3, 1));
    assertEquals(vec.z().x().z().y(), new Vector4.Primitive(3, 1, 3, 2));
    assertEquals(vec.z().x().z().z(), new Vector4.Primitive(3, 1, 3, 3));
    assertEquals(vec.z().x().z().w(), new Vector4.Primitive(3, 1, 3, 4));
    assertEquals(vec.z().x().w().x(), new Vector4.Primitive(3, 1, 4, 1));
    assertEquals(vec.z().x().w().y(), new Vector4.Primitive(3, 1, 4, 2));
    assertEquals(vec.z().x().w().z(), new Vector4.Primitive(3, 1, 4, 3));
    assertEquals(vec.z().x().w().w(), new Vector4.Primitive(3, 1, 4, 4));
    assertEquals(vec.z().y().x().x(), new Vector4.Primitive(3, 2, 1, 1));
    assertEquals(vec.z().y().x().y(), new Vector4.Primitive(3, 2, 1, 2));
    assertEquals(vec.z().y().x().z(), new Vector4.Primitive(3, 2, 1, 3));
    assertEquals(vec.z().y().x().w(), new Vector4.Primitive(3, 2, 1, 4));
    assertEquals(vec.z().y().y().x(), new Vector4.Primitive(3, 2, 2, 1));
    assertEquals(vec.z().y().y().y(), new Vector4.Primitive(3, 2, 2, 2));
    assertEquals(vec.z().y().y().z(), new Vector4.Primitive(3, 2, 2, 3));
    assertEquals(vec.z().y().y().w(), new Vector4.Primitive(3, 2, 2, 4));
    assertEquals(vec.z().y().z().x(), new Vector4.Primitive(3, 2, 3, 1));
    assertEquals(vec.z().y().z().y(), new Vector4.Primitive(3, 2, 3, 2));
    assertEquals(vec.z().y().z().z(), new Vector4.Primitive(3, 2, 3, 3));
    assertEquals(vec.z().y().z().w(), new Vector4.Primitive(3, 2, 3, 4));
    assertEquals(vec.z().y().w().x(), new Vector4.Primitive(3, 2, 4, 1));
    assertEquals(vec.z().y().w().y(), new Vector4.Primitive(3, 2, 4, 2));
    assertEquals(vec.z().y().w().z(), new Vector4.Primitive(3, 2, 4, 3));
    assertEquals(vec.z().y().w().w(), new Vector4.Primitive(3, 2, 4, 4));
    assertEquals(vec.z().z().x().x(), new Vector4.Primitive(3, 3, 1, 1));
    assertEquals(vec.z().z().x().y(), new Vector4.Primitive(3, 3, 1, 2));
    assertEquals(vec.z().z().x().z(), new Vector4.Primitive(3, 3, 1, 3));
    assertEquals(vec.z().z().x().w(), new Vector4.Primitive(3, 3, 1, 4));
    assertEquals(vec.z().z().y().x(), new Vector4.Primitive(3, 3, 2, 1));
    assertEquals(vec.z().z().y().y(), new Vector4.Primitive(3, 3, 2, 2));
    assertEquals(vec.z().z().y().z(), new Vector4.Primitive(3, 3, 2, 3));
    assertEquals(vec.z().z().y().w(), new Vector4.Primitive(3, 3, 2, 4));
    assertEquals(vec.z().z().z().x(), new Vector4.Primitive(3, 3, 3, 1));
    assertEquals(vec.z().z().z().y(), new Vector4.Primitive(3, 3, 3, 2));
    assertEquals(vec.z().z().z().z(), new Vector4.Primitive(3, 3, 3, 3));
    assertEquals(vec.z().z().z().w(), new Vector4.Primitive(3, 3, 3, 4));
    assertEquals(vec.z().z().w().x(), new Vector4.Primitive(3, 3, 4, 1));
    assertEquals(vec.z().z().w().y(), new Vector4.Primitive(3, 3, 4, 2));
    assertEquals(vec.z().z().w().z(), new Vector4.Primitive(3, 3, 4, 3));
    assertEquals(vec.z().z().w().w(), new Vector4.Primitive(3, 3, 4, 4));
    assertEquals(vec.z().w().x().x(), new Vector4.Primitive(3, 4, 1, 1));
    assertEquals(vec.z().w().x().y(), new Vector4.Primitive(3, 4, 1, 2));
    assertEquals(vec.z().w().x().z(), new Vector4.Primitive(3, 4, 1, 3));
    assertEquals(vec.z().w().x().w(), new Vector4.Primitive(3, 4, 1, 4));
    assertEquals(vec.z().w().y().x(), new Vector4.Primitive(3, 4, 2, 1));
    assertEquals(vec.z().w().y().y(), new Vector4.Primitive(3, 4, 2, 2));
    assertEquals(vec.z().w().y().z(), new Vector4.Primitive(3, 4, 2, 3));
    assertEquals(vec.z().w().y().w(), new Vector4.Primitive(3, 4, 2, 4));
    assertEquals(vec.z().w().z().x(), new Vector4.Primitive(3, 4, 3, 1));
    assertEquals(vec.z().w().z().y(), new Vector4.Primitive(3, 4, 3, 2));
    assertEquals(vec.z().w().z().z(), new Vector4.Primitive(3, 4, 3, 3));
    assertEquals(vec.z().w().z().w(), new Vector4.Primitive(3, 4, 3, 4));
    assertEquals(vec.z().w().w().x(), new Vector4.Primitive(3, 4, 4, 1));
    assertEquals(vec.z().w().w().y(), new Vector4.Primitive(3, 4, 4, 2));
    assertEquals(vec.z().w().w().z(), new Vector4.Primitive(3, 4, 4, 3));
    assertEquals(vec.z().w().w().w(), new Vector4.Primitive(3, 4, 4, 4));
    assertEquals(vec.w().x().x().x(), new Vector4.Primitive(4, 1, 1, 1));
    assertEquals(vec.w().x().x().y(), new Vector4.Primitive(4, 1, 1, 2));
    assertEquals(vec.w().x().x().z(), new Vector4.Primitive(4, 1, 1, 3));
    assertEquals(vec.w().x().x().w(), new Vector4.Primitive(4, 1, 1, 4));
    assertEquals(vec.w().x().y().x(), new Vector4.Primitive(4, 1, 2, 1));
    assertEquals(vec.w().x().y().y(), new Vector4.Primitive(4, 1, 2, 2));
    assertEquals(vec.w().x().y().z(), new Vector4.Primitive(4, 1, 2, 3));
    assertEquals(vec.w().x().y().w(), new Vector4.Primitive(4, 1, 2, 4));
    assertEquals(vec.w().x().z().x(), new Vector4.Primitive(4, 1, 3, 1));
    assertEquals(vec.w().x().z().y(), new Vector4.Primitive(4, 1, 3, 2));
    assertEquals(vec.w().x().z().z(), new Vector4.Primitive(4, 1, 3, 3));
    assertEquals(vec.w().x().z().w(), new Vector4.Primitive(4, 1, 3, 4));
    assertEquals(vec.w().x().w().x(), new Vector4.Primitive(4, 1, 4, 1));
    assertEquals(vec.w().x().w().y(), new Vector4.Primitive(4, 1, 4, 2));
    assertEquals(vec.w().x().w().z(), new Vector4.Primitive(4, 1, 4, 3));
    assertEquals(vec.w().x().w().w(), new Vector4.Primitive(4, 1, 4, 4));
    assertEquals(vec.w().y().x().x(), new Vector4.Primitive(4, 2, 1, 1));
    assertEquals(vec.w().y().x().y(), new Vector4.Primitive(4, 2, 1, 2));
    assertEquals(vec.w().y().x().z(), new Vector4.Primitive(4, 2, 1, 3));
    assertEquals(vec.w().y().x().w(), new Vector4.Primitive(4, 2, 1, 4));
    assertEquals(vec.w().y().y().x(), new Vector4.Primitive(4, 2, 2, 1));
    assertEquals(vec.w().y().y().y(), new Vector4.Primitive(4, 2, 2, 2));
    assertEquals(vec.w().y().y().z(), new Vector4.Primitive(4, 2, 2, 3));
    assertEquals(vec.w().y().y().w(), new Vector4.Primitive(4, 2, 2, 4));
    assertEquals(vec.w().y().z().x(), new Vector4.Primitive(4, 2, 3, 1));
    assertEquals(vec.w().y().z().y(), new Vector4.Primitive(4, 2, 3, 2));
    assertEquals(vec.w().y().z().z(), new Vector4.Primitive(4, 2, 3, 3));
    assertEquals(vec.w().y().z().w(), new Vector4.Primitive(4, 2, 3, 4));
    assertEquals(vec.w().y().w().x(), new Vector4.Primitive(4, 2, 4, 1));
    assertEquals(vec.w().y().w().y(), new Vector4.Primitive(4, 2, 4, 2));
    assertEquals(vec.w().y().w().z(), new Vector4.Primitive(4, 2, 4, 3));
    assertEquals(vec.w().y().w().w(), new Vector4.Primitive(4, 2, 4, 4));
    assertEquals(vec.w().z().x().x(), new Vector4.Primitive(4, 3, 1, 1));
    assertEquals(vec.w().z().x().y(), new Vector4.Primitive(4, 3, 1, 2));
    assertEquals(vec.w().z().x().z(), new Vector4.Primitive(4, 3, 1, 3));
    assertEquals(vec.w().z().x().w(), new Vector4.Primitive(4, 3, 1, 4));
    assertEquals(vec.w().z().y().x(), new Vector4.Primitive(4, 3, 2, 1));
    assertEquals(vec.w().z().y().y(), new Vector4.Primitive(4, 3, 2, 2));
    assertEquals(vec.w().z().y().z(), new Vector4.Primitive(4, 3, 2, 3));
    assertEquals(vec.w().z().y().w(), new Vector4.Primitive(4, 3, 2, 4));
    assertEquals(vec.w().z().z().x(), new Vector4.Primitive(4, 3, 3, 1));
    assertEquals(vec.w().z().z().y(), new Vector4.Primitive(4, 3, 3, 2));
    assertEquals(vec.w().z().z().z(), new Vector4.Primitive(4, 3, 3, 3));
    assertEquals(vec.w().z().z().w(), new Vector4.Primitive(4, 3, 3, 4));
    assertEquals(vec.w().z().w().x(), new Vector4.Primitive(4, 3, 4, 1));
    assertEquals(vec.w().z().w().y(), new Vector4.Primitive(4, 3, 4, 2));
    assertEquals(vec.w().z().w().z(), new Vector4.Primitive(4, 3, 4, 3));
    assertEquals(vec.w().z().w().w(), new Vector4.Primitive(4, 3, 4, 4));
    assertEquals(vec.w().w().x().x(), new Vector4.Primitive(4, 4, 1, 1));
    assertEquals(vec.w().w().x().y(), new Vector4.Primitive(4, 4, 1, 2));
    assertEquals(vec.w().w().x().z(), new Vector4.Primitive(4, 4, 1, 3));
    assertEquals(vec.w().w().x().w(), new Vector4.Primitive(4, 4, 1, 4));
    assertEquals(vec.w().w().y().x(), new Vector4.Primitive(4, 4, 2, 1));
    assertEquals(vec.w().w().y().y(), new Vector4.Primitive(4, 4, 2, 2));
    assertEquals(vec.w().w().y().z(), new Vector4.Primitive(4, 4, 2, 3));
    assertEquals(vec.w().w().y().w(), new Vector4.Primitive(4, 4, 2, 4));
    assertEquals(vec.w().w().z().x(), new Vector4.Primitive(4, 4, 3, 1));
    assertEquals(vec.w().w().z().y(), new Vector4.Primitive(4, 4, 3, 2));
    assertEquals(vec.w().w().z().z(), new Vector4.Primitive(4, 4, 3, 3));
    assertEquals(vec.w().w().z().w(), new Vector4.Primitive(4, 4, 3, 4));
    assertEquals(vec.w().w().w().x(), new Vector4.Primitive(4, 4, 4, 1));
    assertEquals(vec.w().w().w().y(), new Vector4.Primitive(4, 4, 4, 2));
    assertEquals(vec.w().w().w().z(), new Vector4.Primitive(4, 4, 4, 3));
    assertEquals(vec.w().w().w().w(), new Vector4.Primitive(4, 4, 4, 4));

  }

  @Test
  @SuppressWarnings("all")
  public void testSwizzleRGBA() {
    assertTrue(vec.r().get() == 1);
    assertTrue(vec.g().get() == 2);
    assertTrue(vec.b().get() == 3);
    assertTrue(vec.a().get() == 4);

    assertEquals(vec.r().r().get(), new Vector2.Primitive(1, 1));
    assertEquals(vec.r().g().get(), new Vector2.Primitive(1, 2));
    assertEquals(vec.r().b().get(), new Vector2.Primitive(1, 3));
    assertEquals(vec.r().a().get(), new Vector2.Primitive(1, 4));
    assertEquals(vec.g().r().get(), new Vector2.Primitive(2, 1));
    assertEquals(vec.g().g().get(), new Vector2.Primitive(2, 2));
    assertEquals(vec.g().b().get(), new Vector2.Primitive(2, 3));
    assertEquals(vec.g().a().get(), new Vector2.Primitive(2, 4));
    assertEquals(vec.b().r().get(), new Vector2.Primitive(3, 1));
    assertEquals(vec.b().g().get(), new Vector2.Primitive(3, 2));
    assertEquals(vec.b().b().get(), new Vector2.Primitive(3, 3));
    assertEquals(vec.b().a().get(), new Vector2.Primitive(3, 4));
    assertEquals(vec.a().r().get(), new Vector2.Primitive(4, 1));
    assertEquals(vec.a().g().get(), new Vector2.Primitive(4, 2));
    assertEquals(vec.a().b().get(), new Vector2.Primitive(4, 3));
    assertEquals(vec.a().a().get(), new Vector2.Primitive(4, 4));

    assertEquals(vec.r().r().r().get(), new Vector3.Primitive(1, 1, 1));
    assertEquals(vec.r().r().g().get(), new Vector3.Primitive(1, 1, 2));
    assertEquals(vec.r().r().b().get(), new Vector3.Primitive(1, 1, 3));
    assertEquals(vec.r().r().a().get(), new Vector3.Primitive(1, 1, 4));
    assertEquals(vec.r().g().r().get(), new Vector3.Primitive(1, 2, 1));
    assertEquals(vec.r().g().g().get(), new Vector3.Primitive(1, 2, 2));
    assertEquals(vec.r().g().b().get(), new Vector3.Primitive(1, 2, 3));
    assertEquals(vec.r().g().a().get(), new Vector3.Primitive(1, 2, 4));
    assertEquals(vec.r().b().r().get(), new Vector3.Primitive(1, 3, 1));
    assertEquals(vec.r().b().g().get(), new Vector3.Primitive(1, 3, 2));
    assertEquals(vec.r().b().b().get(), new Vector3.Primitive(1, 3, 3));
    assertEquals(vec.r().b().a().get(), new Vector3.Primitive(1, 3, 4));
    assertEquals(vec.r().a().r().get(), new Vector3.Primitive(1, 4, 1));
    assertEquals(vec.r().a().g().get(), new Vector3.Primitive(1, 4, 2));
    assertEquals(vec.r().a().b().get(), new Vector3.Primitive(1, 4, 3));
    assertEquals(vec.r().a().a().get(), new Vector3.Primitive(1, 4, 4));
    assertEquals(vec.g().r().r().get(), new Vector3.Primitive(2, 1, 1));
    assertEquals(vec.g().r().g().get(), new Vector3.Primitive(2, 1, 2));
    assertEquals(vec.g().r().b().get(), new Vector3.Primitive(2, 1, 3));
    assertEquals(vec.g().r().a().get(), new Vector3.Primitive(2, 1, 4));
    assertEquals(vec.g().g().r().get(), new Vector3.Primitive(2, 2, 1));
    assertEquals(vec.g().g().g().get(), new Vector3.Primitive(2, 2, 2));
    assertEquals(vec.g().g().b().get(), new Vector3.Primitive(2, 2, 3));
    assertEquals(vec.g().g().a().get(), new Vector3.Primitive(2, 2, 4));
    assertEquals(vec.g().b().r().get(), new Vector3.Primitive(2, 3, 1));
    assertEquals(vec.g().b().g().get(), new Vector3.Primitive(2, 3, 2));
    assertEquals(vec.g().b().b().get(), new Vector3.Primitive(2, 3, 3));
    assertEquals(vec.g().b().a().get(), new Vector3.Primitive(2, 3, 4));
    assertEquals(vec.g().a().r().get(), new Vector3.Primitive(2, 4, 1));
    assertEquals(vec.g().a().g().get(), new Vector3.Primitive(2, 4, 2));
    assertEquals(vec.g().a().b().get(), new Vector3.Primitive(2, 4, 3));
    assertEquals(vec.g().a().a().get(), new Vector3.Primitive(2, 4, 4));
    assertEquals(vec.b().r().r().get(), new Vector3.Primitive(3, 1, 1));
    assertEquals(vec.b().r().g().get(), new Vector3.Primitive(3, 1, 2));
    assertEquals(vec.b().r().b().get(), new Vector3.Primitive(3, 1, 3));
    assertEquals(vec.b().r().a().get(), new Vector3.Primitive(3, 1, 4));
    assertEquals(vec.b().g().r().get(), new Vector3.Primitive(3, 2, 1));
    assertEquals(vec.b().g().g().get(), new Vector3.Primitive(3, 2, 2));
    assertEquals(vec.b().g().b().get(), new Vector3.Primitive(3, 2, 3));
    assertEquals(vec.b().g().a().get(), new Vector3.Primitive(3, 2, 4));
    assertEquals(vec.b().b().r().get(), new Vector3.Primitive(3, 3, 1));
    assertEquals(vec.b().b().g().get(), new Vector3.Primitive(3, 3, 2));
    assertEquals(vec.b().b().b().get(), new Vector3.Primitive(3, 3, 3));
    assertEquals(vec.b().b().a().get(), new Vector3.Primitive(3, 3, 4));
    assertEquals(vec.b().a().r().get(), new Vector3.Primitive(3, 4, 1));
    assertEquals(vec.b().a().g().get(), new Vector3.Primitive(3, 4, 2));
    assertEquals(vec.b().a().b().get(), new Vector3.Primitive(3, 4, 3));
    assertEquals(vec.b().a().a().get(), new Vector3.Primitive(3, 4, 4));
    assertEquals(vec.a().r().r().get(), new Vector3.Primitive(4, 1, 1));
    assertEquals(vec.a().r().g().get(), new Vector3.Primitive(4, 1, 2));
    assertEquals(vec.a().r().b().get(), new Vector3.Primitive(4, 1, 3));
    assertEquals(vec.a().r().a().get(), new Vector3.Primitive(4, 1, 4));
    assertEquals(vec.a().g().r().get(), new Vector3.Primitive(4, 2, 1));
    assertEquals(vec.a().g().g().get(), new Vector3.Primitive(4, 2, 2));
    assertEquals(vec.a().g().b().get(), new Vector3.Primitive(4, 2, 3));
    assertEquals(vec.a().g().a().get(), new Vector3.Primitive(4, 2, 4));
    assertEquals(vec.a().b().r().get(), new Vector3.Primitive(4, 3, 1));
    assertEquals(vec.a().b().g().get(), new Vector3.Primitive(4, 3, 2));
    assertEquals(vec.a().b().b().get(), new Vector3.Primitive(4, 3, 3));
    assertEquals(vec.a().b().a().get(), new Vector3.Primitive(4, 3, 4));
    assertEquals(vec.a().a().r().get(), new Vector3.Primitive(4, 4, 1));
    assertEquals(vec.a().a().g().get(), new Vector3.Primitive(4, 4, 2));
    assertEquals(vec.a().a().b().get(), new Vector3.Primitive(4, 4, 3));
    assertEquals(vec.a().a().a().get(), new Vector3.Primitive(4, 4, 4));

    assertEquals(vec.r().r().r().r(), new Vector4.Primitive(1, 1, 1, 1));
    assertEquals(vec.r().r().r().g(), new Vector4.Primitive(1, 1, 1, 2));
    assertEquals(vec.r().r().r().b(), new Vector4.Primitive(1, 1, 1, 3));
    assertEquals(vec.r().r().r().a(), new Vector4.Primitive(1, 1, 1, 4));
    assertEquals(vec.r().r().g().r(), new Vector4.Primitive(1, 1, 2, 1));
    assertEquals(vec.r().r().g().g(), new Vector4.Primitive(1, 1, 2, 2));
    assertEquals(vec.r().r().g().b(), new Vector4.Primitive(1, 1, 2, 3));
    assertEquals(vec.r().r().g().a(), new Vector4.Primitive(1, 1, 2, 4));
    assertEquals(vec.r().r().b().r(), new Vector4.Primitive(1, 1, 3, 1));
    assertEquals(vec.r().r().b().g(), new Vector4.Primitive(1, 1, 3, 2));
    assertEquals(vec.r().r().b().b(), new Vector4.Primitive(1, 1, 3, 3));
    assertEquals(vec.r().r().b().a(), new Vector4.Primitive(1, 1, 3, 4));
    assertEquals(vec.r().r().a().r(), new Vector4.Primitive(1, 1, 4, 1));
    assertEquals(vec.r().r().a().g(), new Vector4.Primitive(1, 1, 4, 2));
    assertEquals(vec.r().r().a().b(), new Vector4.Primitive(1, 1, 4, 3));
    assertEquals(vec.r().r().a().a(), new Vector4.Primitive(1, 1, 4, 4));
    assertEquals(vec.r().g().r().r(), new Vector4.Primitive(1, 2, 1, 1));
    assertEquals(vec.r().g().r().g(), new Vector4.Primitive(1, 2, 1, 2));
    assertEquals(vec.r().g().r().b(), new Vector4.Primitive(1, 2, 1, 3));
    assertEquals(vec.r().g().r().a(), new Vector4.Primitive(1, 2, 1, 4));
    assertEquals(vec.r().g().g().r(), new Vector4.Primitive(1, 2, 2, 1));
    assertEquals(vec.r().g().g().g(), new Vector4.Primitive(1, 2, 2, 2));
    assertEquals(vec.r().g().g().b(), new Vector4.Primitive(1, 2, 2, 3));
    assertEquals(vec.r().g().g().a(), new Vector4.Primitive(1, 2, 2, 4));
    assertEquals(vec.r().g().b().r(), new Vector4.Primitive(1, 2, 3, 1));
    assertEquals(vec.r().g().b().g(), new Vector4.Primitive(1, 2, 3, 2));
    assertEquals(vec.r().g().b().b(), new Vector4.Primitive(1, 2, 3, 3));
    assertEquals(vec.r().g().b().a(), new Vector4.Primitive(1, 2, 3, 4));
    assertEquals(vec.r().g().a().r(), new Vector4.Primitive(1, 2, 4, 1));
    assertEquals(vec.r().g().a().g(), new Vector4.Primitive(1, 2, 4, 2));
    assertEquals(vec.r().g().a().b(), new Vector4.Primitive(1, 2, 4, 3));
    assertEquals(vec.r().g().a().a(), new Vector4.Primitive(1, 2, 4, 4));
    assertEquals(vec.r().b().r().r(), new Vector4.Primitive(1, 3, 1, 1));
    assertEquals(vec.r().b().r().g(), new Vector4.Primitive(1, 3, 1, 2));
    assertEquals(vec.r().b().r().b(), new Vector4.Primitive(1, 3, 1, 3));
    assertEquals(vec.r().b().r().a(), new Vector4.Primitive(1, 3, 1, 4));
    assertEquals(vec.r().b().g().r(), new Vector4.Primitive(1, 3, 2, 1));
    assertEquals(vec.r().b().g().g(), new Vector4.Primitive(1, 3, 2, 2));
    assertEquals(vec.r().b().g().b(), new Vector4.Primitive(1, 3, 2, 3));
    assertEquals(vec.r().b().g().a(), new Vector4.Primitive(1, 3, 2, 4));
    assertEquals(vec.r().b().b().r(), new Vector4.Primitive(1, 3, 3, 1));
    assertEquals(vec.r().b().b().g(), new Vector4.Primitive(1, 3, 3, 2));
    assertEquals(vec.r().b().b().b(), new Vector4.Primitive(1, 3, 3, 3));
    assertEquals(vec.r().b().b().a(), new Vector4.Primitive(1, 3, 3, 4));
    assertEquals(vec.r().b().a().r(), new Vector4.Primitive(1, 3, 4, 1));
    assertEquals(vec.r().b().a().g(), new Vector4.Primitive(1, 3, 4, 2));
    assertEquals(vec.r().b().a().b(), new Vector4.Primitive(1, 3, 4, 3));
    assertEquals(vec.r().b().a().a(), new Vector4.Primitive(1, 3, 4, 4));
    assertEquals(vec.r().a().r().r(), new Vector4.Primitive(1, 4, 1, 1));
    assertEquals(vec.r().a().r().g(), new Vector4.Primitive(1, 4, 1, 2));
    assertEquals(vec.r().a().r().b(), new Vector4.Primitive(1, 4, 1, 3));
    assertEquals(vec.r().a().r().a(), new Vector4.Primitive(1, 4, 1, 4));
    assertEquals(vec.r().a().g().r(), new Vector4.Primitive(1, 4, 2, 1));
    assertEquals(vec.r().a().g().g(), new Vector4.Primitive(1, 4, 2, 2));
    assertEquals(vec.r().a().g().b(), new Vector4.Primitive(1, 4, 2, 3));
    assertEquals(vec.r().a().g().a(), new Vector4.Primitive(1, 4, 2, 4));
    assertEquals(vec.r().a().b().r(), new Vector4.Primitive(1, 4, 3, 1));
    assertEquals(vec.r().a().b().g(), new Vector4.Primitive(1, 4, 3, 2));
    assertEquals(vec.r().a().b().b(), new Vector4.Primitive(1, 4, 3, 3));
    assertEquals(vec.r().a().b().a(), new Vector4.Primitive(1, 4, 3, 4));
    assertEquals(vec.r().a().a().r(), new Vector4.Primitive(1, 4, 4, 1));
    assertEquals(vec.r().a().a().g(), new Vector4.Primitive(1, 4, 4, 2));
    assertEquals(vec.r().a().a().b(), new Vector4.Primitive(1, 4, 4, 3));
    assertEquals(vec.r().a().a().a(), new Vector4.Primitive(1, 4, 4, 4));
    assertEquals(vec.g().r().r().r(), new Vector4.Primitive(2, 1, 1, 1));
    assertEquals(vec.g().r().r().g(), new Vector4.Primitive(2, 1, 1, 2));
    assertEquals(vec.g().r().r().b(), new Vector4.Primitive(2, 1, 1, 3));
    assertEquals(vec.g().r().r().a(), new Vector4.Primitive(2, 1, 1, 4));
    assertEquals(vec.g().r().g().r(), new Vector4.Primitive(2, 1, 2, 1));
    assertEquals(vec.g().r().g().g(), new Vector4.Primitive(2, 1, 2, 2));
    assertEquals(vec.g().r().g().b(), new Vector4.Primitive(2, 1, 2, 3));
    assertEquals(vec.g().r().g().a(), new Vector4.Primitive(2, 1, 2, 4));
    assertEquals(vec.g().r().b().r(), new Vector4.Primitive(2, 1, 3, 1));
    assertEquals(vec.g().r().b().g(), new Vector4.Primitive(2, 1, 3, 2));
    assertEquals(vec.g().r().b().b(), new Vector4.Primitive(2, 1, 3, 3));
    assertEquals(vec.g().r().b().a(), new Vector4.Primitive(2, 1, 3, 4));
    assertEquals(vec.g().r().a().r(), new Vector4.Primitive(2, 1, 4, 1));
    assertEquals(vec.g().r().a().g(), new Vector4.Primitive(2, 1, 4, 2));
    assertEquals(vec.g().r().a().b(), new Vector4.Primitive(2, 1, 4, 3));
    assertEquals(vec.g().r().a().a(), new Vector4.Primitive(2, 1, 4, 4));
    assertEquals(vec.g().g().r().r(), new Vector4.Primitive(2, 2, 1, 1));
    assertEquals(vec.g().g().r().g(), new Vector4.Primitive(2, 2, 1, 2));
    assertEquals(vec.g().g().r().b(), new Vector4.Primitive(2, 2, 1, 3));
    assertEquals(vec.g().g().r().a(), new Vector4.Primitive(2, 2, 1, 4));
    assertEquals(vec.g().g().g().r(), new Vector4.Primitive(2, 2, 2, 1));
    assertEquals(vec.g().g().g().g(), new Vector4.Primitive(2, 2, 2, 2));
    assertEquals(vec.g().g().g().b(), new Vector4.Primitive(2, 2, 2, 3));
    assertEquals(vec.g().g().g().a(), new Vector4.Primitive(2, 2, 2, 4));
    assertEquals(vec.g().g().b().r(), new Vector4.Primitive(2, 2, 3, 1));
    assertEquals(vec.g().g().b().g(), new Vector4.Primitive(2, 2, 3, 2));
    assertEquals(vec.g().g().b().b(), new Vector4.Primitive(2, 2, 3, 3));
    assertEquals(vec.g().g().b().a(), new Vector4.Primitive(2, 2, 3, 4));
    assertEquals(vec.g().g().a().r(), new Vector4.Primitive(2, 2, 4, 1));
    assertEquals(vec.g().g().a().g(), new Vector4.Primitive(2, 2, 4, 2));
    assertEquals(vec.g().g().a().b(), new Vector4.Primitive(2, 2, 4, 3));
    assertEquals(vec.g().g().a().a(), new Vector4.Primitive(2, 2, 4, 4));
    assertEquals(vec.g().b().r().r(), new Vector4.Primitive(2, 3, 1, 1));
    assertEquals(vec.g().b().r().g(), new Vector4.Primitive(2, 3, 1, 2));
    assertEquals(vec.g().b().r().b(), new Vector4.Primitive(2, 3, 1, 3));
    assertEquals(vec.g().b().r().a(), new Vector4.Primitive(2, 3, 1, 4));
    assertEquals(vec.g().b().g().r(), new Vector4.Primitive(2, 3, 2, 1));
    assertEquals(vec.g().b().g().g(), new Vector4.Primitive(2, 3, 2, 2));
    assertEquals(vec.g().b().g().b(), new Vector4.Primitive(2, 3, 2, 3));
    assertEquals(vec.g().b().g().a(), new Vector4.Primitive(2, 3, 2, 4));
    assertEquals(vec.g().b().b().r(), new Vector4.Primitive(2, 3, 3, 1));
    assertEquals(vec.g().b().b().g(), new Vector4.Primitive(2, 3, 3, 2));
    assertEquals(vec.g().b().b().b(), new Vector4.Primitive(2, 3, 3, 3));
    assertEquals(vec.g().b().b().a(), new Vector4.Primitive(2, 3, 3, 4));
    assertEquals(vec.g().b().a().r(), new Vector4.Primitive(2, 3, 4, 1));
    assertEquals(vec.g().b().a().g(), new Vector4.Primitive(2, 3, 4, 2));
    assertEquals(vec.g().b().a().b(), new Vector4.Primitive(2, 3, 4, 3));
    assertEquals(vec.g().b().a().a(), new Vector4.Primitive(2, 3, 4, 4));
    assertEquals(vec.g().a().r().r(), new Vector4.Primitive(2, 4, 1, 1));
    assertEquals(vec.g().a().r().g(), new Vector4.Primitive(2, 4, 1, 2));
    assertEquals(vec.g().a().r().b(), new Vector4.Primitive(2, 4, 1, 3));
    assertEquals(vec.g().a().r().a(), new Vector4.Primitive(2, 4, 1, 4));
    assertEquals(vec.g().a().g().r(), new Vector4.Primitive(2, 4, 2, 1));
    assertEquals(vec.g().a().g().g(), new Vector4.Primitive(2, 4, 2, 2));
    assertEquals(vec.g().a().g().b(), new Vector4.Primitive(2, 4, 2, 3));
    assertEquals(vec.g().a().g().a(), new Vector4.Primitive(2, 4, 2, 4));
    assertEquals(vec.g().a().b().r(), new Vector4.Primitive(2, 4, 3, 1));
    assertEquals(vec.g().a().b().g(), new Vector4.Primitive(2, 4, 3, 2));
    assertEquals(vec.g().a().b().b(), new Vector4.Primitive(2, 4, 3, 3));
    assertEquals(vec.g().a().b().a(), new Vector4.Primitive(2, 4, 3, 4));
    assertEquals(vec.g().a().a().r(), new Vector4.Primitive(2, 4, 4, 1));
    assertEquals(vec.g().a().a().g(), new Vector4.Primitive(2, 4, 4, 2));
    assertEquals(vec.g().a().a().b(), new Vector4.Primitive(2, 4, 4, 3));
    assertEquals(vec.g().a().a().a(), new Vector4.Primitive(2, 4, 4, 4));
    assertEquals(vec.b().r().r().r(), new Vector4.Primitive(3, 1, 1, 1));
    assertEquals(vec.b().r().r().g(), new Vector4.Primitive(3, 1, 1, 2));
    assertEquals(vec.b().r().r().b(), new Vector4.Primitive(3, 1, 1, 3));
    assertEquals(vec.b().r().r().a(), new Vector4.Primitive(3, 1, 1, 4));
    assertEquals(vec.b().r().g().r(), new Vector4.Primitive(3, 1, 2, 1));
    assertEquals(vec.b().r().g().g(), new Vector4.Primitive(3, 1, 2, 2));
    assertEquals(vec.b().r().g().b(), new Vector4.Primitive(3, 1, 2, 3));
    assertEquals(vec.b().r().g().a(), new Vector4.Primitive(3, 1, 2, 4));
    assertEquals(vec.b().r().b().r(), new Vector4.Primitive(3, 1, 3, 1));
    assertEquals(vec.b().r().b().g(), new Vector4.Primitive(3, 1, 3, 2));
    assertEquals(vec.b().r().b().b(), new Vector4.Primitive(3, 1, 3, 3));
    assertEquals(vec.b().r().b().a(), new Vector4.Primitive(3, 1, 3, 4));
    assertEquals(vec.b().r().a().r(), new Vector4.Primitive(3, 1, 4, 1));
    assertEquals(vec.b().r().a().g(), new Vector4.Primitive(3, 1, 4, 2));
    assertEquals(vec.b().r().a().b(), new Vector4.Primitive(3, 1, 4, 3));
    assertEquals(vec.b().r().a().a(), new Vector4.Primitive(3, 1, 4, 4));
    assertEquals(vec.b().g().r().r(), new Vector4.Primitive(3, 2, 1, 1));
    assertEquals(vec.b().g().r().g(), new Vector4.Primitive(3, 2, 1, 2));
    assertEquals(vec.b().g().r().b(), new Vector4.Primitive(3, 2, 1, 3));
    assertEquals(vec.b().g().r().a(), new Vector4.Primitive(3, 2, 1, 4));
    assertEquals(vec.b().g().g().r(), new Vector4.Primitive(3, 2, 2, 1));
    assertEquals(vec.b().g().g().g(), new Vector4.Primitive(3, 2, 2, 2));
    assertEquals(vec.b().g().g().b(), new Vector4.Primitive(3, 2, 2, 3));
    assertEquals(vec.b().g().g().a(), new Vector4.Primitive(3, 2, 2, 4));
    assertEquals(vec.b().g().b().r(), new Vector4.Primitive(3, 2, 3, 1));
    assertEquals(vec.b().g().b().g(), new Vector4.Primitive(3, 2, 3, 2));
    assertEquals(vec.b().g().b().b(), new Vector4.Primitive(3, 2, 3, 3));
    assertEquals(vec.b().g().b().a(), new Vector4.Primitive(3, 2, 3, 4));
    assertEquals(vec.b().g().a().r(), new Vector4.Primitive(3, 2, 4, 1));
    assertEquals(vec.b().g().a().g(), new Vector4.Primitive(3, 2, 4, 2));
    assertEquals(vec.b().g().a().b(), new Vector4.Primitive(3, 2, 4, 3));
    assertEquals(vec.b().g().a().a(), new Vector4.Primitive(3, 2, 4, 4));
    assertEquals(vec.b().b().r().r(), new Vector4.Primitive(3, 3, 1, 1));
    assertEquals(vec.b().b().r().g(), new Vector4.Primitive(3, 3, 1, 2));
    assertEquals(vec.b().b().r().b(), new Vector4.Primitive(3, 3, 1, 3));
    assertEquals(vec.b().b().r().a(), new Vector4.Primitive(3, 3, 1, 4));
    assertEquals(vec.b().b().g().r(), new Vector4.Primitive(3, 3, 2, 1));
    assertEquals(vec.b().b().g().g(), new Vector4.Primitive(3, 3, 2, 2));
    assertEquals(vec.b().b().g().b(), new Vector4.Primitive(3, 3, 2, 3));
    assertEquals(vec.b().b().g().a(), new Vector4.Primitive(3, 3, 2, 4));
    assertEquals(vec.b().b().b().r(), new Vector4.Primitive(3, 3, 3, 1));
    assertEquals(vec.b().b().b().g(), new Vector4.Primitive(3, 3, 3, 2));
    assertEquals(vec.b().b().b().b(), new Vector4.Primitive(3, 3, 3, 3));
    assertEquals(vec.b().b().b().a(), new Vector4.Primitive(3, 3, 3, 4));
    assertEquals(vec.b().b().a().r(), new Vector4.Primitive(3, 3, 4, 1));
    assertEquals(vec.b().b().a().g(), new Vector4.Primitive(3, 3, 4, 2));
    assertEquals(vec.b().b().a().b(), new Vector4.Primitive(3, 3, 4, 3));
    assertEquals(vec.b().b().a().a(), new Vector4.Primitive(3, 3, 4, 4));
    assertEquals(vec.b().a().r().r(), new Vector4.Primitive(3, 4, 1, 1));
    assertEquals(vec.b().a().r().g(), new Vector4.Primitive(3, 4, 1, 2));
    assertEquals(vec.b().a().r().b(), new Vector4.Primitive(3, 4, 1, 3));
    assertEquals(vec.b().a().r().a(), new Vector4.Primitive(3, 4, 1, 4));
    assertEquals(vec.b().a().g().r(), new Vector4.Primitive(3, 4, 2, 1));
    assertEquals(vec.b().a().g().g(), new Vector4.Primitive(3, 4, 2, 2));
    assertEquals(vec.b().a().g().b(), new Vector4.Primitive(3, 4, 2, 3));
    assertEquals(vec.b().a().g().a(), new Vector4.Primitive(3, 4, 2, 4));
    assertEquals(vec.b().a().b().r(), new Vector4.Primitive(3, 4, 3, 1));
    assertEquals(vec.b().a().b().g(), new Vector4.Primitive(3, 4, 3, 2));
    assertEquals(vec.b().a().b().b(), new Vector4.Primitive(3, 4, 3, 3));
    assertEquals(vec.b().a().b().a(), new Vector4.Primitive(3, 4, 3, 4));
    assertEquals(vec.b().a().a().r(), new Vector4.Primitive(3, 4, 4, 1));
    assertEquals(vec.b().a().a().g(), new Vector4.Primitive(3, 4, 4, 2));
    assertEquals(vec.b().a().a().b(), new Vector4.Primitive(3, 4, 4, 3));
    assertEquals(vec.b().a().a().a(), new Vector4.Primitive(3, 4, 4, 4));
    assertEquals(vec.a().r().r().r(), new Vector4.Primitive(4, 1, 1, 1));
    assertEquals(vec.a().r().r().g(), new Vector4.Primitive(4, 1, 1, 2));
    assertEquals(vec.a().r().r().b(), new Vector4.Primitive(4, 1, 1, 3));
    assertEquals(vec.a().r().r().a(), new Vector4.Primitive(4, 1, 1, 4));
    assertEquals(vec.a().r().g().r(), new Vector4.Primitive(4, 1, 2, 1));
    assertEquals(vec.a().r().g().g(), new Vector4.Primitive(4, 1, 2, 2));
    assertEquals(vec.a().r().g().b(), new Vector4.Primitive(4, 1, 2, 3));
    assertEquals(vec.a().r().g().a(), new Vector4.Primitive(4, 1, 2, 4));
    assertEquals(vec.a().r().b().r(), new Vector4.Primitive(4, 1, 3, 1));
    assertEquals(vec.a().r().b().g(), new Vector4.Primitive(4, 1, 3, 2));
    assertEquals(vec.a().r().b().b(), new Vector4.Primitive(4, 1, 3, 3));
    assertEquals(vec.a().r().b().a(), new Vector4.Primitive(4, 1, 3, 4));
    assertEquals(vec.a().r().a().r(), new Vector4.Primitive(4, 1, 4, 1));
    assertEquals(vec.a().r().a().g(), new Vector4.Primitive(4, 1, 4, 2));
    assertEquals(vec.a().r().a().b(), new Vector4.Primitive(4, 1, 4, 3));
    assertEquals(vec.a().r().a().a(), new Vector4.Primitive(4, 1, 4, 4));
    assertEquals(vec.a().g().r().r(), new Vector4.Primitive(4, 2, 1, 1));
    assertEquals(vec.a().g().r().g(), new Vector4.Primitive(4, 2, 1, 2));
    assertEquals(vec.a().g().r().b(), new Vector4.Primitive(4, 2, 1, 3));
    assertEquals(vec.a().g().r().a(), new Vector4.Primitive(4, 2, 1, 4));
    assertEquals(vec.a().g().g().r(), new Vector4.Primitive(4, 2, 2, 1));
    assertEquals(vec.a().g().g().g(), new Vector4.Primitive(4, 2, 2, 2));
    assertEquals(vec.a().g().g().b(), new Vector4.Primitive(4, 2, 2, 3));
    assertEquals(vec.a().g().g().a(), new Vector4.Primitive(4, 2, 2, 4));
    assertEquals(vec.a().g().b().r(), new Vector4.Primitive(4, 2, 3, 1));
    assertEquals(vec.a().g().b().g(), new Vector4.Primitive(4, 2, 3, 2));
    assertEquals(vec.a().g().b().b(), new Vector4.Primitive(4, 2, 3, 3));
    assertEquals(vec.a().g().b().a(), new Vector4.Primitive(4, 2, 3, 4));
    assertEquals(vec.a().g().a().r(), new Vector4.Primitive(4, 2, 4, 1));
    assertEquals(vec.a().g().a().g(), new Vector4.Primitive(4, 2, 4, 2));
    assertEquals(vec.a().g().a().b(), new Vector4.Primitive(4, 2, 4, 3));
    assertEquals(vec.a().g().a().a(), new Vector4.Primitive(4, 2, 4, 4));
    assertEquals(vec.a().b().r().r(), new Vector4.Primitive(4, 3, 1, 1));
    assertEquals(vec.a().b().r().g(), new Vector4.Primitive(4, 3, 1, 2));
    assertEquals(vec.a().b().r().b(), new Vector4.Primitive(4, 3, 1, 3));
    assertEquals(vec.a().b().r().a(), new Vector4.Primitive(4, 3, 1, 4));
    assertEquals(vec.a().b().g().r(), new Vector4.Primitive(4, 3, 2, 1));
    assertEquals(vec.a().b().g().g(), new Vector4.Primitive(4, 3, 2, 2));
    assertEquals(vec.a().b().g().b(), new Vector4.Primitive(4, 3, 2, 3));
    assertEquals(vec.a().b().g().a(), new Vector4.Primitive(4, 3, 2, 4));
    assertEquals(vec.a().b().b().r(), new Vector4.Primitive(4, 3, 3, 1));
    assertEquals(vec.a().b().b().g(), new Vector4.Primitive(4, 3, 3, 2));
    assertEquals(vec.a().b().b().b(), new Vector4.Primitive(4, 3, 3, 3));
    assertEquals(vec.a().b().b().a(), new Vector4.Primitive(4, 3, 3, 4));
    assertEquals(vec.a().b().a().r(), new Vector4.Primitive(4, 3, 4, 1));
    assertEquals(vec.a().b().a().g(), new Vector4.Primitive(4, 3, 4, 2));
    assertEquals(vec.a().b().a().b(), new Vector4.Primitive(4, 3, 4, 3));
    assertEquals(vec.a().b().a().a(), new Vector4.Primitive(4, 3, 4, 4));
    assertEquals(vec.a().a().r().r(), new Vector4.Primitive(4, 4, 1, 1));
    assertEquals(vec.a().a().r().g(), new Vector4.Primitive(4, 4, 1, 2));
    assertEquals(vec.a().a().r().b(), new Vector4.Primitive(4, 4, 1, 3));
    assertEquals(vec.a().a().r().a(), new Vector4.Primitive(4, 4, 1, 4));
    assertEquals(vec.a().a().g().r(), new Vector4.Primitive(4, 4, 2, 1));
    assertEquals(vec.a().a().g().g(), new Vector4.Primitive(4, 4, 2, 2));
    assertEquals(vec.a().a().g().b(), new Vector4.Primitive(4, 4, 2, 3));
    assertEquals(vec.a().a().g().a(), new Vector4.Primitive(4, 4, 2, 4));
    assertEquals(vec.a().a().b().r(), new Vector4.Primitive(4, 4, 3, 1));
    assertEquals(vec.a().a().b().g(), new Vector4.Primitive(4, 4, 3, 2));
    assertEquals(vec.a().a().b().b(), new Vector4.Primitive(4, 4, 3, 3));
    assertEquals(vec.a().a().b().a(), new Vector4.Primitive(4, 4, 3, 4));
    assertEquals(vec.a().a().a().r(), new Vector4.Primitive(4, 4, 4, 1));
    assertEquals(vec.a().a().a().g(), new Vector4.Primitive(4, 4, 4, 2));
    assertEquals(vec.a().a().a().b(), new Vector4.Primitive(4, 4, 4, 3));
    assertEquals(vec.a().a().a().a(), new Vector4.Primitive(4, 4, 4, 4));

  }

  @Test
  @SuppressWarnings("all")
  public void testSwizzleSTPQ() {
    assertTrue(vec.s().get() == 1);
    assertTrue(vec.t().get() == 2);
    assertTrue(vec.p().get() == 3);
    assertTrue(vec.q().get() == 4);

    assertEquals(vec.s().s().get(), new Vector2.Primitive(1, 1));
    assertEquals(vec.s().t().get(), new Vector2.Primitive(1, 2));
    assertEquals(vec.s().p().get(), new Vector2.Primitive(1, 3));
    assertEquals(vec.s().q().get(), new Vector2.Primitive(1, 4));
    assertEquals(vec.t().s().get(), new Vector2.Primitive(2, 1));
    assertEquals(vec.t().t().get(), new Vector2.Primitive(2, 2));
    assertEquals(vec.t().p().get(), new Vector2.Primitive(2, 3));
    assertEquals(vec.t().q().get(), new Vector2.Primitive(2, 4));
    assertEquals(vec.p().s().get(), new Vector2.Primitive(3, 1));
    assertEquals(vec.p().t().get(), new Vector2.Primitive(3, 2));
    assertEquals(vec.p().p().get(), new Vector2.Primitive(3, 3));
    assertEquals(vec.p().q().get(), new Vector2.Primitive(3, 4));
    assertEquals(vec.q().s().get(), new Vector2.Primitive(4, 1));
    assertEquals(vec.q().t().get(), new Vector2.Primitive(4, 2));
    assertEquals(vec.q().p().get(), new Vector2.Primitive(4, 3));
    assertEquals(vec.q().q().get(), new Vector2.Primitive(4, 4));

    assertEquals(vec.s().s().s().get(), new Vector3.Primitive(1, 1, 1));
    assertEquals(vec.s().s().t().get(), new Vector3.Primitive(1, 1, 2));
    assertEquals(vec.s().s().p().get(), new Vector3.Primitive(1, 1, 3));
    assertEquals(vec.s().s().q().get(), new Vector3.Primitive(1, 1, 4));
    assertEquals(vec.s().t().s().get(), new Vector3.Primitive(1, 2, 1));
    assertEquals(vec.s().t().t().get(), new Vector3.Primitive(1, 2, 2));
    assertEquals(vec.s().t().p().get(), new Vector3.Primitive(1, 2, 3));
    assertEquals(vec.s().t().q().get(), new Vector3.Primitive(1, 2, 4));
    assertEquals(vec.s().p().s().get(), new Vector3.Primitive(1, 3, 1));
    assertEquals(vec.s().p().t().get(), new Vector3.Primitive(1, 3, 2));
    assertEquals(vec.s().p().p().get(), new Vector3.Primitive(1, 3, 3));
    assertEquals(vec.s().p().q().get(), new Vector3.Primitive(1, 3, 4));
    assertEquals(vec.s().q().s().get(), new Vector3.Primitive(1, 4, 1));
    assertEquals(vec.s().q().t().get(), new Vector3.Primitive(1, 4, 2));
    assertEquals(vec.s().q().p().get(), new Vector3.Primitive(1, 4, 3));
    assertEquals(vec.s().q().q().get(), new Vector3.Primitive(1, 4, 4));
    assertEquals(vec.t().s().s().get(), new Vector3.Primitive(2, 1, 1));
    assertEquals(vec.t().s().t().get(), new Vector3.Primitive(2, 1, 2));
    assertEquals(vec.t().s().p().get(), new Vector3.Primitive(2, 1, 3));
    assertEquals(vec.t().s().q().get(), new Vector3.Primitive(2, 1, 4));
    assertEquals(vec.t().t().s().get(), new Vector3.Primitive(2, 2, 1));
    assertEquals(vec.t().t().t().get(), new Vector3.Primitive(2, 2, 2));
    assertEquals(vec.t().t().p().get(), new Vector3.Primitive(2, 2, 3));
    assertEquals(vec.t().t().q().get(), new Vector3.Primitive(2, 2, 4));
    assertEquals(vec.t().p().s().get(), new Vector3.Primitive(2, 3, 1));
    assertEquals(vec.t().p().t().get(), new Vector3.Primitive(2, 3, 2));
    assertEquals(vec.t().p().p().get(), new Vector3.Primitive(2, 3, 3));
    assertEquals(vec.t().p().q().get(), new Vector3.Primitive(2, 3, 4));
    assertEquals(vec.t().q().s().get(), new Vector3.Primitive(2, 4, 1));
    assertEquals(vec.t().q().t().get(), new Vector3.Primitive(2, 4, 2));
    assertEquals(vec.t().q().p().get(), new Vector3.Primitive(2, 4, 3));
    assertEquals(vec.t().q().q().get(), new Vector3.Primitive(2, 4, 4));
    assertEquals(vec.p().s().s().get(), new Vector3.Primitive(3, 1, 1));
    assertEquals(vec.p().s().t().get(), new Vector3.Primitive(3, 1, 2));
    assertEquals(vec.p().s().p().get(), new Vector3.Primitive(3, 1, 3));
    assertEquals(vec.p().s().q().get(), new Vector3.Primitive(3, 1, 4));
    assertEquals(vec.p().t().s().get(), new Vector3.Primitive(3, 2, 1));
    assertEquals(vec.p().t().t().get(), new Vector3.Primitive(3, 2, 2));
    assertEquals(vec.p().t().p().get(), new Vector3.Primitive(3, 2, 3));
    assertEquals(vec.p().t().q().get(), new Vector3.Primitive(3, 2, 4));
    assertEquals(vec.p().p().s().get(), new Vector3.Primitive(3, 3, 1));
    assertEquals(vec.p().p().t().get(), new Vector3.Primitive(3, 3, 2));
    assertEquals(vec.p().p().p().get(), new Vector3.Primitive(3, 3, 3));
    assertEquals(vec.p().p().q().get(), new Vector3.Primitive(3, 3, 4));
    assertEquals(vec.p().q().s().get(), new Vector3.Primitive(3, 4, 1));
    assertEquals(vec.p().q().t().get(), new Vector3.Primitive(3, 4, 2));
    assertEquals(vec.p().q().p().get(), new Vector3.Primitive(3, 4, 3));
    assertEquals(vec.p().q().q().get(), new Vector3.Primitive(3, 4, 4));
    assertEquals(vec.q().s().s().get(), new Vector3.Primitive(4, 1, 1));
    assertEquals(vec.q().s().t().get(), new Vector3.Primitive(4, 1, 2));
    assertEquals(vec.q().s().p().get(), new Vector3.Primitive(4, 1, 3));
    assertEquals(vec.q().s().q().get(), new Vector3.Primitive(4, 1, 4));
    assertEquals(vec.q().t().s().get(), new Vector3.Primitive(4, 2, 1));
    assertEquals(vec.q().t().t().get(), new Vector3.Primitive(4, 2, 2));
    assertEquals(vec.q().t().p().get(), new Vector3.Primitive(4, 2, 3));
    assertEquals(vec.q().t().q().get(), new Vector3.Primitive(4, 2, 4));
    assertEquals(vec.q().p().s().get(), new Vector3.Primitive(4, 3, 1));
    assertEquals(vec.q().p().t().get(), new Vector3.Primitive(4, 3, 2));
    assertEquals(vec.q().p().p().get(), new Vector3.Primitive(4, 3, 3));
    assertEquals(vec.q().p().q().get(), new Vector3.Primitive(4, 3, 4));
    assertEquals(vec.q().q().s().get(), new Vector3.Primitive(4, 4, 1));
    assertEquals(vec.q().q().t().get(), new Vector3.Primitive(4, 4, 2));
    assertEquals(vec.q().q().p().get(), new Vector3.Primitive(4, 4, 3));
    assertEquals(vec.q().q().q().get(), new Vector3.Primitive(4, 4, 4));

    assertEquals(vec.s().s().s().s(), new Vector4.Primitive(1, 1, 1, 1));
    assertEquals(vec.s().s().s().t(), new Vector4.Primitive(1, 1, 1, 2));
    assertEquals(vec.s().s().s().p(), new Vector4.Primitive(1, 1, 1, 3));
    assertEquals(vec.s().s().s().q(), new Vector4.Primitive(1, 1, 1, 4));
    assertEquals(vec.s().s().t().s(), new Vector4.Primitive(1, 1, 2, 1));
    assertEquals(vec.s().s().t().t(), new Vector4.Primitive(1, 1, 2, 2));
    assertEquals(vec.s().s().t().p(), new Vector4.Primitive(1, 1, 2, 3));
    assertEquals(vec.s().s().t().q(), new Vector4.Primitive(1, 1, 2, 4));
    assertEquals(vec.s().s().p().s(), new Vector4.Primitive(1, 1, 3, 1));
    assertEquals(vec.s().s().p().t(), new Vector4.Primitive(1, 1, 3, 2));
    assertEquals(vec.s().s().p().p(), new Vector4.Primitive(1, 1, 3, 3));
    assertEquals(vec.s().s().p().q(), new Vector4.Primitive(1, 1, 3, 4));
    assertEquals(vec.s().s().q().s(), new Vector4.Primitive(1, 1, 4, 1));
    assertEquals(vec.s().s().q().t(), new Vector4.Primitive(1, 1, 4, 2));
    assertEquals(vec.s().s().q().p(), new Vector4.Primitive(1, 1, 4, 3));
    assertEquals(vec.s().s().q().q(), new Vector4.Primitive(1, 1, 4, 4));
    assertEquals(vec.s().t().s().s(), new Vector4.Primitive(1, 2, 1, 1));
    assertEquals(vec.s().t().s().t(), new Vector4.Primitive(1, 2, 1, 2));
    assertEquals(vec.s().t().s().p(), new Vector4.Primitive(1, 2, 1, 3));
    assertEquals(vec.s().t().s().q(), new Vector4.Primitive(1, 2, 1, 4));
    assertEquals(vec.s().t().t().s(), new Vector4.Primitive(1, 2, 2, 1));
    assertEquals(vec.s().t().t().t(), new Vector4.Primitive(1, 2, 2, 2));
    assertEquals(vec.s().t().t().p(), new Vector4.Primitive(1, 2, 2, 3));
    assertEquals(vec.s().t().t().q(), new Vector4.Primitive(1, 2, 2, 4));
    assertEquals(vec.s().t().p().s(), new Vector4.Primitive(1, 2, 3, 1));
    assertEquals(vec.s().t().p().t(), new Vector4.Primitive(1, 2, 3, 2));
    assertEquals(vec.s().t().p().p(), new Vector4.Primitive(1, 2, 3, 3));
    assertEquals(vec.s().t().p().q(), new Vector4.Primitive(1, 2, 3, 4));
    assertEquals(vec.s().t().q().s(), new Vector4.Primitive(1, 2, 4, 1));
    assertEquals(vec.s().t().q().t(), new Vector4.Primitive(1, 2, 4, 2));
    assertEquals(vec.s().t().q().p(), new Vector4.Primitive(1, 2, 4, 3));
    assertEquals(vec.s().t().q().q(), new Vector4.Primitive(1, 2, 4, 4));
    assertEquals(vec.s().p().s().s(), new Vector4.Primitive(1, 3, 1, 1));
    assertEquals(vec.s().p().s().t(), new Vector4.Primitive(1, 3, 1, 2));
    assertEquals(vec.s().p().s().p(), new Vector4.Primitive(1, 3, 1, 3));
    assertEquals(vec.s().p().s().q(), new Vector4.Primitive(1, 3, 1, 4));
    assertEquals(vec.s().p().t().s(), new Vector4.Primitive(1, 3, 2, 1));
    assertEquals(vec.s().p().t().t(), new Vector4.Primitive(1, 3, 2, 2));
    assertEquals(vec.s().p().t().p(), new Vector4.Primitive(1, 3, 2, 3));
    assertEquals(vec.s().p().t().q(), new Vector4.Primitive(1, 3, 2, 4));
    assertEquals(vec.s().p().p().s(), new Vector4.Primitive(1, 3, 3, 1));
    assertEquals(vec.s().p().p().t(), new Vector4.Primitive(1, 3, 3, 2));
    assertEquals(vec.s().p().p().p(), new Vector4.Primitive(1, 3, 3, 3));
    assertEquals(vec.s().p().p().q(), new Vector4.Primitive(1, 3, 3, 4));
    assertEquals(vec.s().p().q().s(), new Vector4.Primitive(1, 3, 4, 1));
    assertEquals(vec.s().p().q().t(), new Vector4.Primitive(1, 3, 4, 2));
    assertEquals(vec.s().p().q().p(), new Vector4.Primitive(1, 3, 4, 3));
    assertEquals(vec.s().p().q().q(), new Vector4.Primitive(1, 3, 4, 4));
    assertEquals(vec.s().q().s().s(), new Vector4.Primitive(1, 4, 1, 1));
    assertEquals(vec.s().q().s().t(), new Vector4.Primitive(1, 4, 1, 2));
    assertEquals(vec.s().q().s().p(), new Vector4.Primitive(1, 4, 1, 3));
    assertEquals(vec.s().q().s().q(), new Vector4.Primitive(1, 4, 1, 4));
    assertEquals(vec.s().q().t().s(), new Vector4.Primitive(1, 4, 2, 1));
    assertEquals(vec.s().q().t().t(), new Vector4.Primitive(1, 4, 2, 2));
    assertEquals(vec.s().q().t().p(), new Vector4.Primitive(1, 4, 2, 3));
    assertEquals(vec.s().q().t().q(), new Vector4.Primitive(1, 4, 2, 4));
    assertEquals(vec.s().q().p().s(), new Vector4.Primitive(1, 4, 3, 1));
    assertEquals(vec.s().q().p().t(), new Vector4.Primitive(1, 4, 3, 2));
    assertEquals(vec.s().q().p().p(), new Vector4.Primitive(1, 4, 3, 3));
    assertEquals(vec.s().q().p().q(), new Vector4.Primitive(1, 4, 3, 4));
    assertEquals(vec.s().q().q().s(), new Vector4.Primitive(1, 4, 4, 1));
    assertEquals(vec.s().q().q().t(), new Vector4.Primitive(1, 4, 4, 2));
    assertEquals(vec.s().q().q().p(), new Vector4.Primitive(1, 4, 4, 3));
    assertEquals(vec.s().q().q().q(), new Vector4.Primitive(1, 4, 4, 4));
    assertEquals(vec.t().s().s().s(), new Vector4.Primitive(2, 1, 1, 1));
    assertEquals(vec.t().s().s().t(), new Vector4.Primitive(2, 1, 1, 2));
    assertEquals(vec.t().s().s().p(), new Vector4.Primitive(2, 1, 1, 3));
    assertEquals(vec.t().s().s().q(), new Vector4.Primitive(2, 1, 1, 4));
    assertEquals(vec.t().s().t().s(), new Vector4.Primitive(2, 1, 2, 1));
    assertEquals(vec.t().s().t().t(), new Vector4.Primitive(2, 1, 2, 2));
    assertEquals(vec.t().s().t().p(), new Vector4.Primitive(2, 1, 2, 3));
    assertEquals(vec.t().s().t().q(), new Vector4.Primitive(2, 1, 2, 4));
    assertEquals(vec.t().s().p().s(), new Vector4.Primitive(2, 1, 3, 1));
    assertEquals(vec.t().s().p().t(), new Vector4.Primitive(2, 1, 3, 2));
    assertEquals(vec.t().s().p().p(), new Vector4.Primitive(2, 1, 3, 3));
    assertEquals(vec.t().s().p().q(), new Vector4.Primitive(2, 1, 3, 4));
    assertEquals(vec.t().s().q().s(), new Vector4.Primitive(2, 1, 4, 1));
    assertEquals(vec.t().s().q().t(), new Vector4.Primitive(2, 1, 4, 2));
    assertEquals(vec.t().s().q().p(), new Vector4.Primitive(2, 1, 4, 3));
    assertEquals(vec.t().s().q().q(), new Vector4.Primitive(2, 1, 4, 4));
    assertEquals(vec.t().t().s().s(), new Vector4.Primitive(2, 2, 1, 1));
    assertEquals(vec.t().t().s().t(), new Vector4.Primitive(2, 2, 1, 2));
    assertEquals(vec.t().t().s().p(), new Vector4.Primitive(2, 2, 1, 3));
    assertEquals(vec.t().t().s().q(), new Vector4.Primitive(2, 2, 1, 4));
    assertEquals(vec.t().t().t().s(), new Vector4.Primitive(2, 2, 2, 1));
    assertEquals(vec.t().t().t().t(), new Vector4.Primitive(2, 2, 2, 2));
    assertEquals(vec.t().t().t().p(), new Vector4.Primitive(2, 2, 2, 3));
    assertEquals(vec.t().t().t().q(), new Vector4.Primitive(2, 2, 2, 4));
    assertEquals(vec.t().t().p().s(), new Vector4.Primitive(2, 2, 3, 1));
    assertEquals(vec.t().t().p().t(), new Vector4.Primitive(2, 2, 3, 2));
    assertEquals(vec.t().t().p().p(), new Vector4.Primitive(2, 2, 3, 3));
    assertEquals(vec.t().t().p().q(), new Vector4.Primitive(2, 2, 3, 4));
    assertEquals(vec.t().t().q().s(), new Vector4.Primitive(2, 2, 4, 1));
    assertEquals(vec.t().t().q().t(), new Vector4.Primitive(2, 2, 4, 2));
    assertEquals(vec.t().t().q().p(), new Vector4.Primitive(2, 2, 4, 3));
    assertEquals(vec.t().t().q().q(), new Vector4.Primitive(2, 2, 4, 4));
    assertEquals(vec.t().p().s().s(), new Vector4.Primitive(2, 3, 1, 1));
    assertEquals(vec.t().p().s().t(), new Vector4.Primitive(2, 3, 1, 2));
    assertEquals(vec.t().p().s().p(), new Vector4.Primitive(2, 3, 1, 3));
    assertEquals(vec.t().p().s().q(), new Vector4.Primitive(2, 3, 1, 4));
    assertEquals(vec.t().p().t().s(), new Vector4.Primitive(2, 3, 2, 1));
    assertEquals(vec.t().p().t().t(), new Vector4.Primitive(2, 3, 2, 2));
    assertEquals(vec.t().p().t().p(), new Vector4.Primitive(2, 3, 2, 3));
    assertEquals(vec.t().p().t().q(), new Vector4.Primitive(2, 3, 2, 4));
    assertEquals(vec.t().p().p().s(), new Vector4.Primitive(2, 3, 3, 1));
    assertEquals(vec.t().p().p().t(), new Vector4.Primitive(2, 3, 3, 2));
    assertEquals(vec.t().p().p().p(), new Vector4.Primitive(2, 3, 3, 3));
    assertEquals(vec.t().p().p().q(), new Vector4.Primitive(2, 3, 3, 4));
    assertEquals(vec.t().p().q().s(), new Vector4.Primitive(2, 3, 4, 1));
    assertEquals(vec.t().p().q().t(), new Vector4.Primitive(2, 3, 4, 2));
    assertEquals(vec.t().p().q().p(), new Vector4.Primitive(2, 3, 4, 3));
    assertEquals(vec.t().p().q().q(), new Vector4.Primitive(2, 3, 4, 4));
    assertEquals(vec.t().q().s().s(), new Vector4.Primitive(2, 4, 1, 1));
    assertEquals(vec.t().q().s().t(), new Vector4.Primitive(2, 4, 1, 2));
    assertEquals(vec.t().q().s().p(), new Vector4.Primitive(2, 4, 1, 3));
    assertEquals(vec.t().q().s().q(), new Vector4.Primitive(2, 4, 1, 4));
    assertEquals(vec.t().q().t().s(), new Vector4.Primitive(2, 4, 2, 1));
    assertEquals(vec.t().q().t().t(), new Vector4.Primitive(2, 4, 2, 2));
    assertEquals(vec.t().q().t().p(), new Vector4.Primitive(2, 4, 2, 3));
    assertEquals(vec.t().q().t().q(), new Vector4.Primitive(2, 4, 2, 4));
    assertEquals(vec.t().q().p().s(), new Vector4.Primitive(2, 4, 3, 1));
    assertEquals(vec.t().q().p().t(), new Vector4.Primitive(2, 4, 3, 2));
    assertEquals(vec.t().q().p().p(), new Vector4.Primitive(2, 4, 3, 3));
    assertEquals(vec.t().q().p().q(), new Vector4.Primitive(2, 4, 3, 4));
    assertEquals(vec.t().q().q().s(), new Vector4.Primitive(2, 4, 4, 1));
    assertEquals(vec.t().q().q().t(), new Vector4.Primitive(2, 4, 4, 2));
    assertEquals(vec.t().q().q().p(), new Vector4.Primitive(2, 4, 4, 3));
    assertEquals(vec.t().q().q().q(), new Vector4.Primitive(2, 4, 4, 4));
    assertEquals(vec.p().s().s().s(), new Vector4.Primitive(3, 1, 1, 1));
    assertEquals(vec.p().s().s().t(), new Vector4.Primitive(3, 1, 1, 2));
    assertEquals(vec.p().s().s().p(), new Vector4.Primitive(3, 1, 1, 3));
    assertEquals(vec.p().s().s().q(), new Vector4.Primitive(3, 1, 1, 4));
    assertEquals(vec.p().s().t().s(), new Vector4.Primitive(3, 1, 2, 1));
    assertEquals(vec.p().s().t().t(), new Vector4.Primitive(3, 1, 2, 2));
    assertEquals(vec.p().s().t().p(), new Vector4.Primitive(3, 1, 2, 3));
    assertEquals(vec.p().s().t().q(), new Vector4.Primitive(3, 1, 2, 4));
    assertEquals(vec.p().s().p().s(), new Vector4.Primitive(3, 1, 3, 1));
    assertEquals(vec.p().s().p().t(), new Vector4.Primitive(3, 1, 3, 2));
    assertEquals(vec.p().s().p().p(), new Vector4.Primitive(3, 1, 3, 3));
    assertEquals(vec.p().s().p().q(), new Vector4.Primitive(3, 1, 3, 4));
    assertEquals(vec.p().s().q().s(), new Vector4.Primitive(3, 1, 4, 1));
    assertEquals(vec.p().s().q().t(), new Vector4.Primitive(3, 1, 4, 2));
    assertEquals(vec.p().s().q().p(), new Vector4.Primitive(3, 1, 4, 3));
    assertEquals(vec.p().s().q().q(), new Vector4.Primitive(3, 1, 4, 4));
    assertEquals(vec.p().t().s().s(), new Vector4.Primitive(3, 2, 1, 1));
    assertEquals(vec.p().t().s().t(), new Vector4.Primitive(3, 2, 1, 2));
    assertEquals(vec.p().t().s().p(), new Vector4.Primitive(3, 2, 1, 3));
    assertEquals(vec.p().t().s().q(), new Vector4.Primitive(3, 2, 1, 4));
    assertEquals(vec.p().t().t().s(), new Vector4.Primitive(3, 2, 2, 1));
    assertEquals(vec.p().t().t().t(), new Vector4.Primitive(3, 2, 2, 2));
    assertEquals(vec.p().t().t().p(), new Vector4.Primitive(3, 2, 2, 3));
    assertEquals(vec.p().t().t().q(), new Vector4.Primitive(3, 2, 2, 4));
    assertEquals(vec.p().t().p().s(), new Vector4.Primitive(3, 2, 3, 1));
    assertEquals(vec.p().t().p().t(), new Vector4.Primitive(3, 2, 3, 2));
    assertEquals(vec.p().t().p().p(), new Vector4.Primitive(3, 2, 3, 3));
    assertEquals(vec.p().t().p().q(), new Vector4.Primitive(3, 2, 3, 4));
    assertEquals(vec.p().t().q().s(), new Vector4.Primitive(3, 2, 4, 1));
    assertEquals(vec.p().t().q().t(), new Vector4.Primitive(3, 2, 4, 2));
    assertEquals(vec.p().t().q().p(), new Vector4.Primitive(3, 2, 4, 3));
    assertEquals(vec.p().t().q().q(), new Vector4.Primitive(3, 2, 4, 4));
    assertEquals(vec.p().p().s().s(), new Vector4.Primitive(3, 3, 1, 1));
    assertEquals(vec.p().p().s().t(), new Vector4.Primitive(3, 3, 1, 2));
    assertEquals(vec.p().p().s().p(), new Vector4.Primitive(3, 3, 1, 3));
    assertEquals(vec.p().p().s().q(), new Vector4.Primitive(3, 3, 1, 4));
    assertEquals(vec.p().p().t().s(), new Vector4.Primitive(3, 3, 2, 1));
    assertEquals(vec.p().p().t().t(), new Vector4.Primitive(3, 3, 2, 2));
    assertEquals(vec.p().p().t().p(), new Vector4.Primitive(3, 3, 2, 3));
    assertEquals(vec.p().p().t().q(), new Vector4.Primitive(3, 3, 2, 4));
    assertEquals(vec.p().p().p().s(), new Vector4.Primitive(3, 3, 3, 1));
    assertEquals(vec.p().p().p().t(), new Vector4.Primitive(3, 3, 3, 2));
    assertEquals(vec.p().p().p().p(), new Vector4.Primitive(3, 3, 3, 3));
    assertEquals(vec.p().p().p().q(), new Vector4.Primitive(3, 3, 3, 4));
    assertEquals(vec.p().p().q().s(), new Vector4.Primitive(3, 3, 4, 1));
    assertEquals(vec.p().p().q().t(), new Vector4.Primitive(3, 3, 4, 2));
    assertEquals(vec.p().p().q().p(), new Vector4.Primitive(3, 3, 4, 3));
    assertEquals(vec.p().p().q().q(), new Vector4.Primitive(3, 3, 4, 4));
    assertEquals(vec.p().q().s().s(), new Vector4.Primitive(3, 4, 1, 1));
    assertEquals(vec.p().q().s().t(), new Vector4.Primitive(3, 4, 1, 2));
    assertEquals(vec.p().q().s().p(), new Vector4.Primitive(3, 4, 1, 3));
    assertEquals(vec.p().q().s().q(), new Vector4.Primitive(3, 4, 1, 4));
    assertEquals(vec.p().q().t().s(), new Vector4.Primitive(3, 4, 2, 1));
    assertEquals(vec.p().q().t().t(), new Vector4.Primitive(3, 4, 2, 2));
    assertEquals(vec.p().q().t().p(), new Vector4.Primitive(3, 4, 2, 3));
    assertEquals(vec.p().q().t().q(), new Vector4.Primitive(3, 4, 2, 4));
    assertEquals(vec.p().q().p().s(), new Vector4.Primitive(3, 4, 3, 1));
    assertEquals(vec.p().q().p().t(), new Vector4.Primitive(3, 4, 3, 2));
    assertEquals(vec.p().q().p().p(), new Vector4.Primitive(3, 4, 3, 3));
    assertEquals(vec.p().q().p().q(), new Vector4.Primitive(3, 4, 3, 4));
    assertEquals(vec.p().q().q().s(), new Vector4.Primitive(3, 4, 4, 1));
    assertEquals(vec.p().q().q().t(), new Vector4.Primitive(3, 4, 4, 2));
    assertEquals(vec.p().q().q().p(), new Vector4.Primitive(3, 4, 4, 3));
    assertEquals(vec.p().q().q().q(), new Vector4.Primitive(3, 4, 4, 4));
    assertEquals(vec.q().s().s().s(), new Vector4.Primitive(4, 1, 1, 1));
    assertEquals(vec.q().s().s().t(), new Vector4.Primitive(4, 1, 1, 2));
    assertEquals(vec.q().s().s().p(), new Vector4.Primitive(4, 1, 1, 3));
    assertEquals(vec.q().s().s().q(), new Vector4.Primitive(4, 1, 1, 4));
    assertEquals(vec.q().s().t().s(), new Vector4.Primitive(4, 1, 2, 1));
    assertEquals(vec.q().s().t().t(), new Vector4.Primitive(4, 1, 2, 2));
    assertEquals(vec.q().s().t().p(), new Vector4.Primitive(4, 1, 2, 3));
    assertEquals(vec.q().s().t().q(), new Vector4.Primitive(4, 1, 2, 4));
    assertEquals(vec.q().s().p().s(), new Vector4.Primitive(4, 1, 3, 1));
    assertEquals(vec.q().s().p().t(), new Vector4.Primitive(4, 1, 3, 2));
    assertEquals(vec.q().s().p().p(), new Vector4.Primitive(4, 1, 3, 3));
    assertEquals(vec.q().s().p().q(), new Vector4.Primitive(4, 1, 3, 4));
    assertEquals(vec.q().s().q().s(), new Vector4.Primitive(4, 1, 4, 1));
    assertEquals(vec.q().s().q().t(), new Vector4.Primitive(4, 1, 4, 2));
    assertEquals(vec.q().s().q().p(), new Vector4.Primitive(4, 1, 4, 3));
    assertEquals(vec.q().s().q().q(), new Vector4.Primitive(4, 1, 4, 4));
    assertEquals(vec.q().t().s().s(), new Vector4.Primitive(4, 2, 1, 1));
    assertEquals(vec.q().t().s().t(), new Vector4.Primitive(4, 2, 1, 2));
    assertEquals(vec.q().t().s().p(), new Vector4.Primitive(4, 2, 1, 3));
    assertEquals(vec.q().t().s().q(), new Vector4.Primitive(4, 2, 1, 4));
    assertEquals(vec.q().t().t().s(), new Vector4.Primitive(4, 2, 2, 1));
    assertEquals(vec.q().t().t().t(), new Vector4.Primitive(4, 2, 2, 2));
    assertEquals(vec.q().t().t().p(), new Vector4.Primitive(4, 2, 2, 3));
    assertEquals(vec.q().t().t().q(), new Vector4.Primitive(4, 2, 2, 4));
    assertEquals(vec.q().t().p().s(), new Vector4.Primitive(4, 2, 3, 1));
    assertEquals(vec.q().t().p().t(), new Vector4.Primitive(4, 2, 3, 2));
    assertEquals(vec.q().t().p().p(), new Vector4.Primitive(4, 2, 3, 3));
    assertEquals(vec.q().t().p().q(), new Vector4.Primitive(4, 2, 3, 4));
    assertEquals(vec.q().t().q().s(), new Vector4.Primitive(4, 2, 4, 1));
    assertEquals(vec.q().t().q().t(), new Vector4.Primitive(4, 2, 4, 2));
    assertEquals(vec.q().t().q().p(), new Vector4.Primitive(4, 2, 4, 3));
    assertEquals(vec.q().t().q().q(), new Vector4.Primitive(4, 2, 4, 4));
    assertEquals(vec.q().p().s().s(), new Vector4.Primitive(4, 3, 1, 1));
    assertEquals(vec.q().p().s().t(), new Vector4.Primitive(4, 3, 1, 2));
    assertEquals(vec.q().p().s().p(), new Vector4.Primitive(4, 3, 1, 3));
    assertEquals(vec.q().p().s().q(), new Vector4.Primitive(4, 3, 1, 4));
    assertEquals(vec.q().p().t().s(), new Vector4.Primitive(4, 3, 2, 1));
    assertEquals(vec.q().p().t().t(), new Vector4.Primitive(4, 3, 2, 2));
    assertEquals(vec.q().p().t().p(), new Vector4.Primitive(4, 3, 2, 3));
    assertEquals(vec.q().p().t().q(), new Vector4.Primitive(4, 3, 2, 4));
    assertEquals(vec.q().p().p().s(), new Vector4.Primitive(4, 3, 3, 1));
    assertEquals(vec.q().p().p().t(), new Vector4.Primitive(4, 3, 3, 2));
    assertEquals(vec.q().p().p().p(), new Vector4.Primitive(4, 3, 3, 3));
    assertEquals(vec.q().p().p().q(), new Vector4.Primitive(4, 3, 3, 4));
    assertEquals(vec.q().p().q().s(), new Vector4.Primitive(4, 3, 4, 1));
    assertEquals(vec.q().p().q().t(), new Vector4.Primitive(4, 3, 4, 2));
    assertEquals(vec.q().p().q().p(), new Vector4.Primitive(4, 3, 4, 3));
    assertEquals(vec.q().p().q().q(), new Vector4.Primitive(4, 3, 4, 4));
    assertEquals(vec.q().q().s().s(), new Vector4.Primitive(4, 4, 1, 1));
    assertEquals(vec.q().q().s().t(), new Vector4.Primitive(4, 4, 1, 2));
    assertEquals(vec.q().q().s().p(), new Vector4.Primitive(4, 4, 1, 3));
    assertEquals(vec.q().q().s().q(), new Vector4.Primitive(4, 4, 1, 4));
    assertEquals(vec.q().q().t().s(), new Vector4.Primitive(4, 4, 2, 1));
    assertEquals(vec.q().q().t().t(), new Vector4.Primitive(4, 4, 2, 2));
    assertEquals(vec.q().q().t().p(), new Vector4.Primitive(4, 4, 2, 3));
    assertEquals(vec.q().q().t().q(), new Vector4.Primitive(4, 4, 2, 4));
    assertEquals(vec.q().q().p().s(), new Vector4.Primitive(4, 4, 3, 1));
    assertEquals(vec.q().q().p().t(), new Vector4.Primitive(4, 4, 3, 2));
    assertEquals(vec.q().q().p().p(), new Vector4.Primitive(4, 4, 3, 3));
    assertEquals(vec.q().q().p().q(), new Vector4.Primitive(4, 4, 3, 4));
    assertEquals(vec.q().q().q().s(), new Vector4.Primitive(4, 4, 4, 1));
    assertEquals(vec.q().q().q().t(), new Vector4.Primitive(4, 4, 4, 2));
    assertEquals(vec.q().q().q().p(), new Vector4.Primitive(4, 4, 4, 3));
    assertEquals(vec.q().q().q().q(), new Vector4.Primitive(4, 4, 4, 4));

  }

  @Test
  public void testAdd() {
    Vector4.Primitive added = vec.add(1);
    assertTrue(added.getX() == 2);
    assertTrue(added.getY() == 3);
    assertTrue(added.getZ() == 4);
    assertTrue(added.getW() == 5);

    added = vec.add(vec);
    assertTrue(added.getX() == 2);
    assertTrue(added.getY() == 4);
    assertTrue(added.getZ() == 6);
    assertTrue(added.getW() == 8);
  }

  @Test
  public void testSub() {
    Vector4.Primitive subtracted = vec.sub(1);
    assertTrue(subtracted.getX() == 0);
    assertTrue(subtracted.getY() == 1);
    assertTrue(subtracted.getZ() == 2);
    assertTrue(subtracted.getW() == 3);

    subtracted = vec.sub(vec);
    assertTrue(subtracted.getX() == 0);
    assertTrue(subtracted.getY() == 0);
    assertTrue(subtracted.getZ() == 0);
    assertTrue(subtracted.getW() == 0);
  }

  @Test
  public void testMul() {
    Vector4.Primitive scaled = vec.mul(3);
    assertTrue(scaled.getX() == 3);
    assertTrue(scaled.getY() == 6);
    assertTrue(scaled.getZ() == 9);
    assertTrue(scaled.getW() == 12);

    scaled = vec.mul(vec);
    assertTrue(scaled.getX() == 1);
    assertTrue(scaled.getY() == 4);
    assertTrue(scaled.getZ() == 9);
    assertTrue(scaled.getW() == 16);
  }

  @Test
  public void testDiv() {
    Vector4.Primitive divided = vec.div(2);
    assertTrue(divided.getX() == 0.5);
    assertTrue(divided.getY() == 1);
    assertTrue(divided.getZ() == 1.5);
    assertTrue(divided.getW() == 2);

    divided = vec.div(vec);
    assertTrue(divided.getX() == 1);
    assertTrue(divided.getY() == 1);
    assertTrue(divided.getZ() == 1);
    assertTrue(divided.getW() == 1);
  }

  @Test
  public void testNeg() {
    Vector4.Primitive negated = vec.neg();

    assertTrue(negated.getX() == -1);
    assertTrue(negated.getY() == -2);
    assertTrue(negated.getZ() == -3);
    assertTrue(negated.getW() == -4);
  }

  @Test
  public void testNormalize() {
    Vector4.Primitive normalized = vec.normalize();

    assertEquals(normalized.getX(), 0.18257418583505536, 10e-8);
    assertEquals(normalized.getY(), 0.3651483716701107, 10e-8);
    assertEquals(normalized.getZ(), 0.5477225575051661, 10e-8);
    assertEquals(normalized.getW(), 0.7302967433402214, 10e-8);
  }

  @Test
  public void testLength() {
    float length = vec.length();

    assertEquals(length, 5.477225575051661, 10e-7);
  }

  @Test
  public void testDot() {
    float dot = vec.dot(vec);

    assertTrue(dot == 30);
  }

  @Test
  public void testBooleanOperations() {
    BVector4.Primitive lessThan = vec.isLessThan(new Vector4.Primitive(1, 3, 3, 3));
    assertFalse(lessThan.getX());
    assertTrue(lessThan.getY());
    assertFalse(lessThan.getZ());
    assertFalse(lessThan.getW());

    BVector4.Primitive lessThanOrEqual = vec.isLessThanOrEqual(new Vector4.Primitive(1, 3, 3, 3));
    assertTrue(lessThanOrEqual.getX());
    assertTrue(lessThanOrEqual.getY());
    assertTrue(lessThanOrEqual.getZ());
    assertFalse(lessThanOrEqual.getW());

    BVector4.Primitive greaterThan = vec.isGreaterThan(new Vector4.Primitive(1, 1, 1, 1));
    assertFalse(greaterThan.getX());
    assertTrue(greaterThan.getY());
    assertTrue(greaterThan.getZ());
    assertTrue(greaterThan.getW());

    BVector4.Primitive greaterThanOrEqual = vec.isGreaterThanOrEqual(new Vector4.Primitive(1, 1, 1, 1));
    assertTrue(greaterThanOrEqual.getX());
    assertTrue(greaterThanOrEqual.getY());
    assertTrue(greaterThanOrEqual.getZ());
    assertTrue(greaterThanOrEqual.getW());

    BVector4.Primitive equalComponentwise = vec.isEqualComponentwise(new Vector4.Primitive(1, 1, 1, 1));
    assertTrue(equalComponentwise.getX());
    assertFalse(equalComponentwise.getY());
    assertFalse(equalComponentwise.getZ());
    assertFalse(equalComponentwise.getW());

    BVector4.Primitive notEqualComponentwise = vec.isNotEqualComponentwise(new Vector4.Primitive(1, 1, 1, 1));
    assertFalse(notEqualComponentwise.getX());
    assertTrue(notEqualComponentwise.getY());
    assertTrue(notEqualComponentwise.getZ());
    assertTrue(notEqualComponentwise.getW());
  }

  @Test
  @SuppressWarnings("all")
  public void testEquals() {
    Vector4.Primitive equal = new Vector4.Primitive(1, 2, 3, 4);
    assertEquals(vec, equal);

    Vector4.Primitive unequal = new Vector4.Primitive(3, 4, 5, 6);
    assertFalse(vec.equals(unequal));

    assertFalse(vec.equals(null));

    assertFalse(vec.equals("A string"));
  }

  @Test
  public void testHashCode() {
    Vector4.Primitive equal = new Vector4.Primitive(1, 2, 3, 4);

    assertEquals(vec, equal);
    assertEquals(vec.hashCode(), equal.hashCode());
  }

  @Test
  public void testToString() {
    String toString = vec.toString();
    assertEquals(toString, "vec4(1.0, 2.0, 3.0, 4.0)");
  }
}
